// Code generated by ent, DO NOT EDIT.

package agentcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldUpdatedAt, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldAgentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldOrderID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSourceType, v))
}

// SourceAmount applies equality check predicate on the "source_amount" field. It's identical to SourceAmountEQ.
func SourceAmount(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSourceAmount, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionAmount applies equality check predicate on the "commission_amount" field. It's identical to CommissionAmountEQ.
func CommissionAmount(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldStatus, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSettledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldUpdatedAt, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldAgentID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldUserID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotNull(FieldOrderID))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceAmountEQ applies the EQ predicate on the "source_amount" field.
func SourceAmountEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSourceAmount, v))
}

// SourceAmountNEQ applies the NEQ predicate on the "source_amount" field.
func SourceAmountNEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldSourceAmount, v))
}

// SourceAmountIn applies the In predicate on the "source_amount" field.
func SourceAmountIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldSourceAmount, vs...))
}

// SourceAmountNotIn applies the NotIn predicate on the "source_amount" field.
func SourceAmountNotIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldSourceAmount, vs...))
}

// SourceAmountGT applies the GT predicate on the "source_amount" field.
func SourceAmountGT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldSourceAmount, v))
}

// SourceAmountGTE applies the GTE predicate on the "source_amount" field.
func SourceAmountGTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldSourceAmount, v))
}

// SourceAmountLT applies the LT predicate on the "source_amount" field.
func SourceAmountLT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldSourceAmount, v))
}

// SourceAmountLTE applies the LTE predicate on the "source_amount" field.
func SourceAmountLTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldSourceAmount, v))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldCommissionRate, v))
}

// CommissionAmountEQ applies the EQ predicate on the "commission_amount" field.
func CommissionAmountEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// CommissionAmountNEQ applies the NEQ predicate on the "commission_amount" field.
func CommissionAmountNEQ(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldCommissionAmount, v))
}

// CommissionAmountIn applies the In predicate on the "commission_amount" field.
func CommissionAmountIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldCommissionAmount, vs...))
}

// CommissionAmountNotIn applies the NotIn predicate on the "commission_amount" field.
func CommissionAmountNotIn(vs ...float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldCommissionAmount, vs...))
}

// CommissionAmountGT applies the GT predicate on the "commission_amount" field.
func CommissionAmountGT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldCommissionAmount, v))
}

// CommissionAmountGTE applies the GTE predicate on the "commission_amount" field.
func CommissionAmountGTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldCommissionAmount, v))
}

// CommissionAmountLT applies the LT predicate on the "commission_amount" field.
func CommissionAmountLT(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldCommissionAmount, v))
}

// CommissionAmountLTE applies the LTE predicate on the "commission_amount" field.
func CommissionAmountLTE(v float64) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldCommissionAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldContainsFold(FieldStatus, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.AgentCommission {
	return predicate.AgentCommission(sql.FieldNotNull(FieldSettledAt))
}

// HasAgent applies the HasEdge predicate on the "agent" edge.
func HasAgent() predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentTable, AgentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentWith applies the HasEdge predicate on the "agent" edge with a given conditions (other predicates).
func HasAgentWith(preds ...predicate.User) predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := newAgentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.AgentCommission {
	return predicate.AgentCommission(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentCommission) predicate.AgentCommission {
	return predicate.AgentCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentCommission) predicate.AgentCommission {
	return predicate.AgentCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentCommission) predicate.AgentCommission {
	return predicate.AgentCommission(sql.NotPredicates(p))
}
