ALTER TABLE announcements ADD COLUMN IF NOT EXISTS version VARCHAR(50) DEFAULT '';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS category VARCHAR(50) NOT NULL DEFAULT '优化';
ALTER TABLE announcements ADD COLUMN IF NOT EXISTS published_at DATE DEFAULT NULL;
