// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/admininvitecode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdminInviteCodeDelete is the builder for deleting a AdminInviteCode entity.
type AdminInviteCodeDelete struct {
	config
	hooks    []Hook
	mutation *AdminInviteCodeMutation
}

// Where appends a list predicates to the AdminInviteCodeDelete builder.
func (_d *AdminInviteCodeDelete) Where(ps ...predicate.AdminInviteCode) *AdminInviteCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminInviteCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminInviteCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminInviteCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(admininvitecode.Table, sqlgraph.NewFieldSpec(admininvitecode.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminInviteCodeDeleteOne is the builder for deleting a single AdminInviteCode entity.
type AdminInviteCodeDeleteOne struct {
	_d *AdminInviteCodeDelete
}

// Where appends a list predicates to the AdminInviteCodeDelete builder.
func (_d *AdminInviteCodeDeleteOne) Where(ps ...predicate.AdminInviteCode) *AdminInviteCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminInviteCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{admininvitecode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminInviteCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
