// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/admininvitecode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AdminInviteCodeUpdate is the builder for updating AdminInviteCode entities.
type AdminInviteCodeUpdate struct {
	config
	hooks    []Hook
	mutation *AdminInviteCodeMutation
}

// Where appends a list predicates to the AdminInviteCodeUpdate builder.
func (_u *AdminInviteCodeUpdate) Where(ps ...predicate.AdminInviteCode) *AdminInviteCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *AdminInviteCodeUpdate) SetCode(v string) *AdminInviteCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableCode(v *string) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *AdminInviteCodeUpdate) SetSourceName(v string) *AdminInviteCodeUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableSourceName(v *string) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AdminInviteCodeUpdate) SetCreatedBy(v int64) *AdminInviteCodeUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableCreatedBy(v *int64) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *AdminInviteCodeUpdate) SetUsedCount(v int) *AdminInviteCodeUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableUsedCount(v *int) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *AdminInviteCodeUpdate) AddUsedCount(v int) *AdminInviteCodeUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *AdminInviteCodeUpdate) SetMaxUses(v int) *AdminInviteCodeUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableMaxUses(v *int) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *AdminInviteCodeUpdate) AddMaxUses(v int) *AdminInviteCodeUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// ClearMaxUses clears the value of the "max_uses" field.
func (_u *AdminInviteCodeUpdate) ClearMaxUses() *AdminInviteCodeUpdate {
	_u.mutation.ClearMaxUses()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdminInviteCodeUpdate) SetEnabled(v bool) *AdminInviteCodeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableEnabled(v *bool) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AdminInviteCodeUpdate) SetNotes(v string) *AdminInviteCodeUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AdminInviteCodeUpdate) SetNillableNotes(v *string) *AdminInviteCodeUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AdminInviteCodeUpdate) ClearNotes() *AdminInviteCodeUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminInviteCodeUpdate) SetUpdatedAt(v time.Time) *AdminInviteCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AdminInviteCodeUpdate) SetCreatorID(id int64) *AdminInviteCodeUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AdminInviteCodeUpdate) SetCreator(v *User) *AdminInviteCodeUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the AdminInviteCodeMutation object of the builder.
func (_u *AdminInviteCodeUpdate) Mutation() *AdminInviteCodeMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AdminInviteCodeUpdate) ClearCreator() *AdminInviteCodeUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminInviteCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminInviteCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminInviteCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminInviteCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminInviteCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admininvitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminInviteCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := admininvitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceName(); ok {
		if err := admininvitecode.SourceNameValidator(v); err != nil {
			return &ValidationError{Name: "source_name", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.source_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsedCount(); ok {
		if err := admininvitecode.UsedCountValidator(v); err != nil {
			return &ValidationError{Name: "used_count", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.used_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUses(); ok {
		if err := admininvitecode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.max_uses": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminInviteCode.creator"`)
	}
	return nil
}

func (_u *AdminInviteCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admininvitecode.Table, admininvitecode.Columns, sqlgraph.NewFieldSpec(admininvitecode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(admininvitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(admininvitecode.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(admininvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(admininvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(admininvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(admininvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if _u.mutation.MaxUsesCleared() {
		_spec.ClearField(admininvitecode.FieldMaxUses, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(admininvitecode.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(admininvitecode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(admininvitecode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admininvitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admininvitecode.CreatorTable,
			Columns: []string{admininvitecode.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admininvitecode.CreatorTable,
			Columns: []string{admininvitecode.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admininvitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminInviteCodeUpdateOne is the builder for updating a single AdminInviteCode entity.
type AdminInviteCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminInviteCodeMutation
}

// SetCode sets the "code" field.
func (_u *AdminInviteCodeUpdateOne) SetCode(v string) *AdminInviteCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableCode(v *string) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *AdminInviteCodeUpdateOne) SetSourceName(v string) *AdminInviteCodeUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableSourceName(v *string) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AdminInviteCodeUpdateOne) SetCreatedBy(v int64) *AdminInviteCodeUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableCreatedBy(v *int64) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *AdminInviteCodeUpdateOne) SetUsedCount(v int) *AdminInviteCodeUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableUsedCount(v *int) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *AdminInviteCodeUpdateOne) AddUsedCount(v int) *AdminInviteCodeUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *AdminInviteCodeUpdateOne) SetMaxUses(v int) *AdminInviteCodeUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableMaxUses(v *int) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *AdminInviteCodeUpdateOne) AddMaxUses(v int) *AdminInviteCodeUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// ClearMaxUses clears the value of the "max_uses" field.
func (_u *AdminInviteCodeUpdateOne) ClearMaxUses() *AdminInviteCodeUpdateOne {
	_u.mutation.ClearMaxUses()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AdminInviteCodeUpdateOne) SetEnabled(v bool) *AdminInviteCodeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableEnabled(v *bool) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *AdminInviteCodeUpdateOne) SetNotes(v string) *AdminInviteCodeUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *AdminInviteCodeUpdateOne) SetNillableNotes(v *string) *AdminInviteCodeUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *AdminInviteCodeUpdateOne) ClearNotes() *AdminInviteCodeUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminInviteCodeUpdateOne) SetUpdatedAt(v time.Time) *AdminInviteCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AdminInviteCodeUpdateOne) SetCreatorID(id int64) *AdminInviteCodeUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AdminInviteCodeUpdateOne) SetCreator(v *User) *AdminInviteCodeUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the AdminInviteCodeMutation object of the builder.
func (_u *AdminInviteCodeUpdateOne) Mutation() *AdminInviteCodeMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AdminInviteCodeUpdateOne) ClearCreator() *AdminInviteCodeUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the AdminInviteCodeUpdate builder.
func (_u *AdminInviteCodeUpdateOne) Where(ps ...predicate.AdminInviteCode) *AdminInviteCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminInviteCodeUpdateOne) Select(field string, fields ...string) *AdminInviteCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminInviteCode entity.
func (_u *AdminInviteCodeUpdateOne) Save(ctx context.Context) (*AdminInviteCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminInviteCodeUpdateOne) SaveX(ctx context.Context) *AdminInviteCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminInviteCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminInviteCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminInviteCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := admininvitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminInviteCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := admininvitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceName(); ok {
		if err := admininvitecode.SourceNameValidator(v); err != nil {
			return &ValidationError{Name: "source_name", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.source_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsedCount(); ok {
		if err := admininvitecode.UsedCountValidator(v); err != nil {
			return &ValidationError{Name: "used_count", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.used_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxUses(); ok {
		if err := admininvitecode.MaxUsesValidator(v); err != nil {
			return &ValidationError{Name: "max_uses", err: fmt.Errorf(`ent: validator failed for field "AdminInviteCode.max_uses": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminInviteCode.creator"`)
	}
	return nil
}

func (_u *AdminInviteCodeUpdateOne) sqlSave(ctx context.Context) (_node *AdminInviteCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admininvitecode.Table, admininvitecode.Columns, sqlgraph.NewFieldSpec(admininvitecode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminInviteCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admininvitecode.FieldID)
		for _, f := range fields {
			if !admininvitecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != admininvitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(admininvitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(admininvitecode.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(admininvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(admininvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(admininvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(admininvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if _u.mutation.MaxUsesCleared() {
		_spec.ClearField(admininvitecode.FieldMaxUses, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(admininvitecode.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(admininvitecode.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(admininvitecode.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(admininvitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admininvitecode.CreatorTable,
			Columns: []string{admininvitecode.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   admininvitecode.CreatorTable,
			Columns: []string{admininvitecode.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminInviteCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admininvitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
