// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/orgauditlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrgAuditLogUpdate is the builder for updating OrgAuditLog entities.
type OrgAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *OrgAuditLogMutation
}

// Where appends a list predicates to the OrgAuditLogUpdate builder.
func (_u *OrgAuditLogUpdate) Where(ps ...predicate.OrgAuditLog) *OrgAuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OrgAuditLogUpdate) SetOrgID(v int64) *OrgAuditLogUpdate {
	_u.mutation.ResetOrgID()
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableOrgID(v *int64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// AddOrgID adds value to the "org_id" field.
func (_u *OrgAuditLogUpdate) AddOrgID(v int64) *OrgAuditLogUpdate {
	_u.mutation.AddOrgID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrgAuditLogUpdate) SetUserID(v int64) *OrgAuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableUserID(v *int64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrgAuditLogUpdate) AddUserID(v int64) *OrgAuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *OrgAuditLogUpdate) SetMemberID(v int64) *OrgAuditLogUpdate {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableMemberID(v *int64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *OrgAuditLogUpdate) AddMemberID(v int64) *OrgAuditLogUpdate {
	_u.mutation.AddMemberID(v)
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *OrgAuditLogUpdate) ClearMemberID() *OrgAuditLogUpdate {
	_u.mutation.ClearMemberID()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *OrgAuditLogUpdate) SetProjectID(v int64) *OrgAuditLogUpdate {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableProjectID(v *int64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *OrgAuditLogUpdate) AddProjectID(v int64) *OrgAuditLogUpdate {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *OrgAuditLogUpdate) ClearProjectID() *OrgAuditLogUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *OrgAuditLogUpdate) SetUsageLogID(v int64) *OrgAuditLogUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableUsageLogID(v *int64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *OrgAuditLogUpdate) AddUsageLogID(v int64) *OrgAuditLogUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *OrgAuditLogUpdate) ClearUsageLogID() *OrgAuditLogUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAction sets the "action" field.
func (_u *OrgAuditLogUpdate) SetAction(v string) *OrgAuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableAction(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *OrgAuditLogUpdate) SetModel(v string) *OrgAuditLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableModel(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *OrgAuditLogUpdate) ClearModel() *OrgAuditLogUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetAuditMode sets the "audit_mode" field.
func (_u *OrgAuditLogUpdate) SetAuditMode(v string) *OrgAuditLogUpdate {
	_u.mutation.SetAuditMode(v)
	return _u
}

// SetNillableAuditMode sets the "audit_mode" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableAuditMode(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetAuditMode(*v)
	}
	return _u
}

// SetRequestSummary sets the "request_summary" field.
func (_u *OrgAuditLogUpdate) SetRequestSummary(v string) *OrgAuditLogUpdate {
	_u.mutation.SetRequestSummary(v)
	return _u
}

// SetNillableRequestSummary sets the "request_summary" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableRequestSummary(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetRequestSummary(*v)
	}
	return _u
}

// ClearRequestSummary clears the value of the "request_summary" field.
func (_u *OrgAuditLogUpdate) ClearRequestSummary() *OrgAuditLogUpdate {
	_u.mutation.ClearRequestSummary()
	return _u
}

// SetRequestContent sets the "request_content" field.
func (_u *OrgAuditLogUpdate) SetRequestContent(v string) *OrgAuditLogUpdate {
	_u.mutation.SetRequestContent(v)
	return _u
}

// SetNillableRequestContent sets the "request_content" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableRequestContent(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetRequestContent(*v)
	}
	return _u
}

// ClearRequestContent clears the value of the "request_content" field.
func (_u *OrgAuditLogUpdate) ClearRequestContent() *OrgAuditLogUpdate {
	_u.mutation.ClearRequestContent()
	return _u
}

// SetResponseSummary sets the "response_summary" field.
func (_u *OrgAuditLogUpdate) SetResponseSummary(v string) *OrgAuditLogUpdate {
	_u.mutation.SetResponseSummary(v)
	return _u
}

// SetNillableResponseSummary sets the "response_summary" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableResponseSummary(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetResponseSummary(*v)
	}
	return _u
}

// ClearResponseSummary clears the value of the "response_summary" field.
func (_u *OrgAuditLogUpdate) ClearResponseSummary() *OrgAuditLogUpdate {
	_u.mutation.ClearResponseSummary()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *OrgAuditLogUpdate) SetKeywords(v []string) *OrgAuditLogUpdate {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *OrgAuditLogUpdate) AppendKeywords(v []string) *OrgAuditLogUpdate {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *OrgAuditLogUpdate) ClearKeywords() *OrgAuditLogUpdate {
	_u.mutation.ClearKeywords()
	return _u
}

// SetFlagged sets the "flagged" field.
func (_u *OrgAuditLogUpdate) SetFlagged(v bool) *OrgAuditLogUpdate {
	_u.mutation.SetFlagged(v)
	return _u
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableFlagged(v *bool) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetFlagged(*v)
	}
	return _u
}

// SetFlagReason sets the "flag_reason" field.
func (_u *OrgAuditLogUpdate) SetFlagReason(v string) *OrgAuditLogUpdate {
	_u.mutation.SetFlagReason(v)
	return _u
}

// SetNillableFlagReason sets the "flag_reason" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableFlagReason(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetFlagReason(*v)
	}
	return _u
}

// ClearFlagReason clears the value of the "flag_reason" field.
func (_u *OrgAuditLogUpdate) ClearFlagReason() *OrgAuditLogUpdate {
	_u.mutation.ClearFlagReason()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *OrgAuditLogUpdate) SetInputTokens(v int) *OrgAuditLogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableInputTokens(v *int) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *OrgAuditLogUpdate) AddInputTokens(v int) *OrgAuditLogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *OrgAuditLogUpdate) ClearInputTokens() *OrgAuditLogUpdate {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *OrgAuditLogUpdate) SetOutputTokens(v int) *OrgAuditLogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableOutputTokens(v *int) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *OrgAuditLogUpdate) AddOutputTokens(v int) *OrgAuditLogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *OrgAuditLogUpdate) ClearOutputTokens() *OrgAuditLogUpdate {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *OrgAuditLogUpdate) SetCostUsd(v float64) *OrgAuditLogUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableCostUsd(v *float64) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *OrgAuditLogUpdate) AddCostUsd(v float64) *OrgAuditLogUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// ClearCostUsd clears the value of the "cost_usd" field.
func (_u *OrgAuditLogUpdate) ClearCostUsd() *OrgAuditLogUpdate {
	_u.mutation.ClearCostUsd()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *OrgAuditLogUpdate) SetIPAddress(v string) *OrgAuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableIPAddress(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *OrgAuditLogUpdate) ClearIPAddress() *OrgAuditLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OrgAuditLogUpdate) SetUserAgent(v string) *OrgAuditLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OrgAuditLogUpdate) SetNillableUserAgent(v *string) *OrgAuditLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OrgAuditLogUpdate) ClearUserAgent() *OrgAuditLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *OrgAuditLogUpdate) SetDetail(v map[string]interface{}) *OrgAuditLogUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *OrgAuditLogUpdate) ClearDetail() *OrgAuditLogUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the OrgAuditLogMutation object of the builder.
func (_u *OrgAuditLogUpdate) Mutation() *OrgAuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrgAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrgAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgAuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgAuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := orgauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := orgauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditMode(); ok {
		if err := orgauditlog.AuditModeValidator(v); err != nil {
			return &ValidationError{Name: "audit_mode", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.audit_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := orgauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := orgauditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *OrgAuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgauditlog.Table, orgauditlog.Columns, sqlgraph.NewFieldSpec(orgauditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(orgauditlog.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrgID(); ok {
		_spec.AddField(orgauditlog.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(orgauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(orgauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(orgauditlog.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(orgauditlog.FieldMemberID, field.TypeInt64, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(orgauditlog.FieldMemberID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(orgauditlog.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(orgauditlog.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(orgauditlog.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(orgauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(orgauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(orgauditlog.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(orgauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(orgauditlog.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(orgauditlog.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.AuditMode(); ok {
		_spec.SetField(orgauditlog.FieldAuditMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSummary(); ok {
		_spec.SetField(orgauditlog.FieldRequestSummary, field.TypeString, value)
	}
	if _u.mutation.RequestSummaryCleared() {
		_spec.ClearField(orgauditlog.FieldRequestSummary, field.TypeString)
	}
	if value, ok := _u.mutation.RequestContent(); ok {
		_spec.SetField(orgauditlog.FieldRequestContent, field.TypeString, value)
	}
	if _u.mutation.RequestContentCleared() {
		_spec.ClearField(orgauditlog.FieldRequestContent, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseSummary(); ok {
		_spec.SetField(orgauditlog.FieldResponseSummary, field.TypeString, value)
	}
	if _u.mutation.ResponseSummaryCleared() {
		_spec.ClearField(orgauditlog.FieldResponseSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(orgauditlog.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgauditlog.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(orgauditlog.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Flagged(); ok {
		_spec.SetField(orgauditlog.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FlagReason(); ok {
		_spec.SetField(orgauditlog.FieldFlagReason, field.TypeString, value)
	}
	if _u.mutation.FlagReasonCleared() {
		_spec.ClearField(orgauditlog.FieldFlagReason, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(orgauditlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(orgauditlog.FieldInputTokens, field.TypeInt, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(orgauditlog.FieldInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(orgauditlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(orgauditlog.FieldOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(orgauditlog.FieldOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(orgauditlog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(orgauditlog.FieldCostUsd, field.TypeFloat64, value)
	}
	if _u.mutation.CostUsdCleared() {
		_spec.ClearField(orgauditlog.FieldCostUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(orgauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(orgauditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(orgauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(orgauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(orgauditlog.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(orgauditlog.FieldDetail, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrgAuditLogUpdateOne is the builder for updating a single OrgAuditLog entity.
type OrgAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrgAuditLogMutation
}

// SetOrgID sets the "org_id" field.
func (_u *OrgAuditLogUpdateOne) SetOrgID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetOrgID()
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableOrgID(v *int64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// AddOrgID adds value to the "org_id" field.
func (_u *OrgAuditLogUpdateOne) AddOrgID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.AddOrgID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrgAuditLogUpdateOne) SetUserID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableUserID(v *int64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrgAuditLogUpdateOne) AddUserID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *OrgAuditLogUpdateOne) SetMemberID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableMemberID(v *int64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *OrgAuditLogUpdateOne) AddMemberID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.AddMemberID(v)
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *OrgAuditLogUpdateOne) ClearMemberID() *OrgAuditLogUpdateOne {
	_u.mutation.ClearMemberID()
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *OrgAuditLogUpdateOne) SetProjectID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableProjectID(v *int64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *OrgAuditLogUpdateOne) AddProjectID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *OrgAuditLogUpdateOne) ClearProjectID() *OrgAuditLogUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *OrgAuditLogUpdateOne) SetUsageLogID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableUsageLogID(v *int64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *OrgAuditLogUpdateOne) AddUsageLogID(v int64) *OrgAuditLogUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *OrgAuditLogUpdateOne) ClearUsageLogID() *OrgAuditLogUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetAction sets the "action" field.
func (_u *OrgAuditLogUpdateOne) SetAction(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableAction(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *OrgAuditLogUpdateOne) SetModel(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableModel(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *OrgAuditLogUpdateOne) ClearModel() *OrgAuditLogUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetAuditMode sets the "audit_mode" field.
func (_u *OrgAuditLogUpdateOne) SetAuditMode(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetAuditMode(v)
	return _u
}

// SetNillableAuditMode sets the "audit_mode" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableAuditMode(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetAuditMode(*v)
	}
	return _u
}

// SetRequestSummary sets the "request_summary" field.
func (_u *OrgAuditLogUpdateOne) SetRequestSummary(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetRequestSummary(v)
	return _u
}

// SetNillableRequestSummary sets the "request_summary" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableRequestSummary(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestSummary(*v)
	}
	return _u
}

// ClearRequestSummary clears the value of the "request_summary" field.
func (_u *OrgAuditLogUpdateOne) ClearRequestSummary() *OrgAuditLogUpdateOne {
	_u.mutation.ClearRequestSummary()
	return _u
}

// SetRequestContent sets the "request_content" field.
func (_u *OrgAuditLogUpdateOne) SetRequestContent(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetRequestContent(v)
	return _u
}

// SetNillableRequestContent sets the "request_content" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableRequestContent(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetRequestContent(*v)
	}
	return _u
}

// ClearRequestContent clears the value of the "request_content" field.
func (_u *OrgAuditLogUpdateOne) ClearRequestContent() *OrgAuditLogUpdateOne {
	_u.mutation.ClearRequestContent()
	return _u
}

// SetResponseSummary sets the "response_summary" field.
func (_u *OrgAuditLogUpdateOne) SetResponseSummary(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetResponseSummary(v)
	return _u
}

// SetNillableResponseSummary sets the "response_summary" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableResponseSummary(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetResponseSummary(*v)
	}
	return _u
}

// ClearResponseSummary clears the value of the "response_summary" field.
func (_u *OrgAuditLogUpdateOne) ClearResponseSummary() *OrgAuditLogUpdateOne {
	_u.mutation.ClearResponseSummary()
	return _u
}

// SetKeywords sets the "keywords" field.
func (_u *OrgAuditLogUpdateOne) SetKeywords(v []string) *OrgAuditLogUpdateOne {
	_u.mutation.SetKeywords(v)
	return _u
}

// AppendKeywords appends value to the "keywords" field.
func (_u *OrgAuditLogUpdateOne) AppendKeywords(v []string) *OrgAuditLogUpdateOne {
	_u.mutation.AppendKeywords(v)
	return _u
}

// ClearKeywords clears the value of the "keywords" field.
func (_u *OrgAuditLogUpdateOne) ClearKeywords() *OrgAuditLogUpdateOne {
	_u.mutation.ClearKeywords()
	return _u
}

// SetFlagged sets the "flagged" field.
func (_u *OrgAuditLogUpdateOne) SetFlagged(v bool) *OrgAuditLogUpdateOne {
	_u.mutation.SetFlagged(v)
	return _u
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableFlagged(v *bool) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetFlagged(*v)
	}
	return _u
}

// SetFlagReason sets the "flag_reason" field.
func (_u *OrgAuditLogUpdateOne) SetFlagReason(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetFlagReason(v)
	return _u
}

// SetNillableFlagReason sets the "flag_reason" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableFlagReason(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetFlagReason(*v)
	}
	return _u
}

// ClearFlagReason clears the value of the "flag_reason" field.
func (_u *OrgAuditLogUpdateOne) ClearFlagReason() *OrgAuditLogUpdateOne {
	_u.mutation.ClearFlagReason()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *OrgAuditLogUpdateOne) SetInputTokens(v int) *OrgAuditLogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableInputTokens(v *int) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *OrgAuditLogUpdateOne) AddInputTokens(v int) *OrgAuditLogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// ClearInputTokens clears the value of the "input_tokens" field.
func (_u *OrgAuditLogUpdateOne) ClearInputTokens() *OrgAuditLogUpdateOne {
	_u.mutation.ClearInputTokens()
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *OrgAuditLogUpdateOne) SetOutputTokens(v int) *OrgAuditLogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableOutputTokens(v *int) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *OrgAuditLogUpdateOne) AddOutputTokens(v int) *OrgAuditLogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// ClearOutputTokens clears the value of the "output_tokens" field.
func (_u *OrgAuditLogUpdateOne) ClearOutputTokens() *OrgAuditLogUpdateOne {
	_u.mutation.ClearOutputTokens()
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *OrgAuditLogUpdateOne) SetCostUsd(v float64) *OrgAuditLogUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableCostUsd(v *float64) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *OrgAuditLogUpdateOne) AddCostUsd(v float64) *OrgAuditLogUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// ClearCostUsd clears the value of the "cost_usd" field.
func (_u *OrgAuditLogUpdateOne) ClearCostUsd() *OrgAuditLogUpdateOne {
	_u.mutation.ClearCostUsd()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *OrgAuditLogUpdateOne) SetIPAddress(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableIPAddress(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *OrgAuditLogUpdateOne) ClearIPAddress() *OrgAuditLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OrgAuditLogUpdateOne) SetUserAgent(v string) *OrgAuditLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OrgAuditLogUpdateOne) SetNillableUserAgent(v *string) *OrgAuditLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OrgAuditLogUpdateOne) ClearUserAgent() *OrgAuditLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetDetail sets the "detail" field.
func (_u *OrgAuditLogUpdateOne) SetDetail(v map[string]interface{}) *OrgAuditLogUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *OrgAuditLogUpdateOne) ClearDetail() *OrgAuditLogUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the OrgAuditLogMutation object of the builder.
func (_u *OrgAuditLogUpdateOne) Mutation() *OrgAuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrgAuditLogUpdate builder.
func (_u *OrgAuditLogUpdateOne) Where(ps ...predicate.OrgAuditLog) *OrgAuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrgAuditLogUpdateOne) Select(field string, fields ...string) *OrgAuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrgAuditLog entity.
func (_u *OrgAuditLogUpdateOne) Save(ctx context.Context) (*OrgAuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgAuditLogUpdateOne) SaveX(ctx context.Context) *OrgAuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrgAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgAuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := orgauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := orgauditlog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuditMode(); ok {
		if err := orgauditlog.AuditModeValidator(v); err != nil {
			return &ValidationError{Name: "audit_mode", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.audit_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IPAddress(); ok {
		if err := orgauditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := orgauditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OrgAuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (_u *OrgAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *OrgAuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgauditlog.Table, orgauditlog.Columns, sqlgraph.NewFieldSpec(orgauditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrgAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgauditlog.FieldID)
		for _, f := range fields {
			if !orgauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orgauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(orgauditlog.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrgID(); ok {
		_spec.AddField(orgauditlog.FieldOrgID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(orgauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(orgauditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(orgauditlog.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(orgauditlog.FieldMemberID, field.TypeInt64, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(orgauditlog.FieldMemberID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(orgauditlog.FieldProjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(orgauditlog.FieldProjectID, field.TypeInt64, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(orgauditlog.FieldProjectID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(orgauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(orgauditlog.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(orgauditlog.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(orgauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(orgauditlog.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(orgauditlog.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.AuditMode(); ok {
		_spec.SetField(orgauditlog.FieldAuditMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSummary(); ok {
		_spec.SetField(orgauditlog.FieldRequestSummary, field.TypeString, value)
	}
	if _u.mutation.RequestSummaryCleared() {
		_spec.ClearField(orgauditlog.FieldRequestSummary, field.TypeString)
	}
	if value, ok := _u.mutation.RequestContent(); ok {
		_spec.SetField(orgauditlog.FieldRequestContent, field.TypeString, value)
	}
	if _u.mutation.RequestContentCleared() {
		_spec.ClearField(orgauditlog.FieldRequestContent, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseSummary(); ok {
		_spec.SetField(orgauditlog.FieldResponseSummary, field.TypeString, value)
	}
	if _u.mutation.ResponseSummaryCleared() {
		_spec.ClearField(orgauditlog.FieldResponseSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Keywords(); ok {
		_spec.SetField(orgauditlog.FieldKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgauditlog.FieldKeywords, value)
		})
	}
	if _u.mutation.KeywordsCleared() {
		_spec.ClearField(orgauditlog.FieldKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Flagged(); ok {
		_spec.SetField(orgauditlog.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FlagReason(); ok {
		_spec.SetField(orgauditlog.FieldFlagReason, field.TypeString, value)
	}
	if _u.mutation.FlagReasonCleared() {
		_spec.ClearField(orgauditlog.FieldFlagReason, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(orgauditlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(orgauditlog.FieldInputTokens, field.TypeInt, value)
	}
	if _u.mutation.InputTokensCleared() {
		_spec.ClearField(orgauditlog.FieldInputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(orgauditlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(orgauditlog.FieldOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.OutputTokensCleared() {
		_spec.ClearField(orgauditlog.FieldOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(orgauditlog.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(orgauditlog.FieldCostUsd, field.TypeFloat64, value)
	}
	if _u.mutation.CostUsdCleared() {
		_spec.ClearField(orgauditlog.FieldCostUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(orgauditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(orgauditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(orgauditlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(orgauditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(orgauditlog.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(orgauditlog.FieldDetail, field.TypeJSON)
	}
	_node = &OrgAuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
