// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/orgauditlog"
	"github.com/Wei-Shaw/sub2api/ent/orgmember"
	"github.com/Wei-Shaw/sub2api/ent/orgproject"
	"github.com/Wei-Shaw/sub2api/ent/orgsubscription"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrganizationCreate is the builder for creating a Organization entity.
type OrganizationCreate struct {
	config
	mutation *OrganizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationCreate) SetCreatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCreatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrganizationCreate) SetUpdatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableUpdatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrganizationCreate) SetDeletedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDeletedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OrganizationCreate) SetName(v string) *OrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *OrganizationCreate) SetSlug(v string) *OrganizationCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OrganizationCreate) SetDescription(v string) *OrganizationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDescription(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *OrganizationCreate) SetOwnerUserID(v int64) *OrganizationCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetBillingMode sets the "billing_mode" field.
func (_c *OrganizationCreate) SetBillingMode(v string) *OrganizationCreate {
	_c.mutation.SetBillingMode(v)
	return _c
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableBillingMode(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetBillingMode(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *OrganizationCreate) SetBalance(v float64) *OrganizationCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableBalance(v *float64) *OrganizationCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (_c *OrganizationCreate) SetMonthlyBudgetUsd(v float64) *OrganizationCreate {
	_c.mutation.SetMonthlyBudgetUsd(v)
	return _c
}

// SetNillableMonthlyBudgetUsd sets the "monthly_budget_usd" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableMonthlyBudgetUsd(v *float64) *OrganizationCreate {
	if v != nil {
		_c.SetMonthlyBudgetUsd(*v)
	}
	return _c
}

// SetMaxMembers sets the "max_members" field.
func (_c *OrganizationCreate) SetMaxMembers(v int) *OrganizationCreate {
	_c.mutation.SetMaxMembers(v)
	return _c
}

// SetNillableMaxMembers sets the "max_members" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableMaxMembers(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetMaxMembers(*v)
	}
	return _c
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (_c *OrganizationCreate) SetMaxAPIKeys(v int) *OrganizationCreate {
	_c.mutation.SetMaxAPIKeys(v)
	return _c
}

// SetNillableMaxAPIKeys sets the "max_api_keys" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableMaxAPIKeys(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetMaxAPIKeys(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrganizationCreate) SetStatus(v string) *OrganizationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableStatus(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAuditMode sets the "audit_mode" field.
func (_c *OrganizationCreate) SetAuditMode(v string) *OrganizationCreate {
	_c.mutation.SetAuditMode(v)
	return _c
}

// SetNillableAuditMode sets the "audit_mode" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableAuditMode(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetAuditMode(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *OrganizationCreate) SetOwnerID(id int64) *OrganizationCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *OrganizationCreate) SetOwner(v *User) *OrganizationCreate {
	return _c.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the OrgMember entity by IDs.
func (_c *OrganizationCreate) AddMemberIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the OrgMember entity.
func (_c *OrganizationCreate) AddMembers(v ...*OrgMember) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the OrgSubscription entity by IDs.
func (_c *OrganizationCreate) AddSubscriptionIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the OrgSubscription entity.
func (_c *OrganizationCreate) AddSubscriptions(v ...*OrgSubscription) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *OrganizationCreate) AddAPIKeyIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *OrganizationCreate) AddAPIKeys(v ...*APIKey) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddProjectIDs adds the "projects" edge to the OrgProject entity by IDs.
func (_c *OrganizationCreate) AddProjectIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the OrgProject entity.
func (_c *OrganizationCreate) AddProjects(v ...*OrgProject) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the OrgAuditLog entity by IDs.
func (_c *OrganizationCreate) AddAuditLogIDs(ids ...int64) *OrganizationCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the OrgAuditLog entity.
func (_c *OrganizationCreate) AddAuditLogs(v ...*OrgAuditLog) *OrganizationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_c *OrganizationCreate) Mutation() *OrganizationMutation {
	return _c.mutation
}

// Save creates the Organization in the database.
func (_c *OrganizationCreate) Save(ctx context.Context) (*Organization, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationCreate) SaveX(ctx context.Context) *Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if organization.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized organization.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := organization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if organization.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized organization.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := organization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.BillingMode(); !ok {
		v := organization.DefaultBillingMode
		_c.mutation.SetBillingMode(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := organization.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		v := organization.DefaultMaxMembers
		_c.mutation.SetMaxMembers(v)
	}
	if _, ok := _c.mutation.MaxAPIKeys(); !ok {
		v := organization.DefaultMaxAPIKeys
		_c.mutation.SetMaxAPIKeys(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := organization.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AuditMode(); !ok {
		v := organization.DefaultAuditMode
		_c.mutation.SetAuditMode(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Organization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Organization.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Organization.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Organization.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := organization.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Organization.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "Organization.owner_user_id"`)}
	}
	if _, ok := _c.mutation.BillingMode(); !ok {
		return &ValidationError{Name: "billing_mode", err: errors.New(`ent: missing required field "Organization.billing_mode"`)}
	}
	if v, ok := _c.mutation.BillingMode(); ok {
		if err := organization.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "Organization.billing_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Organization.balance"`)}
	}
	if _, ok := _c.mutation.MaxMembers(); !ok {
		return &ValidationError{Name: "max_members", err: errors.New(`ent: missing required field "Organization.max_members"`)}
	}
	if _, ok := _c.mutation.MaxAPIKeys(); !ok {
		return &ValidationError{Name: "max_api_keys", err: errors.New(`ent: missing required field "Organization.max_api_keys"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Organization.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuditMode(); !ok {
		return &ValidationError{Name: "audit_mode", err: errors.New(`ent: missing required field "Organization.audit_mode"`)}
	}
	if v, ok := _c.mutation.AuditMode(); ok {
		if err := organization.AuditModeValidator(v); err != nil {
			return &ValidationError{Name: "audit_mode", err: fmt.Errorf(`ent: validator failed for field "Organization.audit_mode": %w`, err)}
		}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Organization.owner"`)}
	}
	return nil
}

func (_c *OrganizationCreate) sqlSave(ctx context.Context) (*Organization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationCreate) createSpec() (*Organization, *sqlgraph.CreateSpec) {
	var (
		_node = &Organization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organization.Table, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(organization.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(organization.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(organization.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.BillingMode(); ok {
		_spec.SetField(organization.FieldBillingMode, field.TypeString, value)
		_node.BillingMode = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(organization.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.MonthlyBudgetUsd(); ok {
		_spec.SetField(organization.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
		_node.MonthlyBudgetUsd = &value
	}
	if value, ok := _c.mutation.MaxMembers(); ok {
		_spec.SetField(organization.FieldMaxMembers, field.TypeInt, value)
		_node.MaxMembers = value
	}
	if value, ok := _c.mutation.MaxAPIKeys(); ok {
		_spec.SetField(organization.FieldMaxAPIKeys, field.TypeInt, value)
		_node.MaxAPIKeys = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AuditMode(); ok {
		_spec.SetField(organization.FieldAuditMode, field.TypeString, value)
		_node.AuditMode = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organization.OwnerTable,
			Columns: []string{organization.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.SubscriptionsTable,
			Columns: []string{organization.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgsubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.APIKeysTable,
			Columns: []string{organization.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.ProjectsTable,
			Columns: []string{organization.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgproject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.AuditLogsTable,
			Columns: []string{organization.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orgauditlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Organization.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationCreate) OnConflict(opts ...sql.ConflictOption) *OrganizationUpsertOne {
	_c.conflict = opts
	return &OrganizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationCreate) OnConflictColumns(columns ...string) *OrganizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationUpsertOne{
		create: _c,
	}
}

type (
	// OrganizationUpsertOne is the builder for "upsert"-ing
	//  one Organization node.
	OrganizationUpsertOne struct {
		create *OrganizationCreate
	}

	// OrganizationUpsert is the "OnConflict" setter.
	OrganizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsert) SetUpdatedAt(v time.Time) *OrganizationUpsert {
	u.Set(organization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateUpdatedAt() *OrganizationUpsert {
	u.SetExcluded(organization.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrganizationUpsert) SetDeletedAt(v time.Time) *OrganizationUpsert {
	u.Set(organization.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateDeletedAt() *OrganizationUpsert {
	u.SetExcluded(organization.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrganizationUpsert) ClearDeletedAt() *OrganizationUpsert {
	u.SetNull(organization.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *OrganizationUpsert) SetName(v string) *OrganizationUpsert {
	u.Set(organization.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateName() *OrganizationUpsert {
	u.SetExcluded(organization.FieldName)
	return u
}

// SetSlug sets the "slug" field.
func (u *OrganizationUpsert) SetSlug(v string) *OrganizationUpsert {
	u.Set(organization.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateSlug() *OrganizationUpsert {
	u.SetExcluded(organization.FieldSlug)
	return u
}

// SetDescription sets the "description" field.
func (u *OrganizationUpsert) SetDescription(v string) *OrganizationUpsert {
	u.Set(organization.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateDescription() *OrganizationUpsert {
	u.SetExcluded(organization.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *OrganizationUpsert) ClearDescription() *OrganizationUpsert {
	u.SetNull(organization.FieldDescription)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsert) SetOwnerUserID(v int64) *OrganizationUpsert {
	u.Set(organization.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateOwnerUserID() *OrganizationUpsert {
	u.SetExcluded(organization.FieldOwnerUserID)
	return u
}

// SetBillingMode sets the "billing_mode" field.
func (u *OrganizationUpsert) SetBillingMode(v string) *OrganizationUpsert {
	u.Set(organization.FieldBillingMode, v)
	return u
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateBillingMode() *OrganizationUpsert {
	u.SetExcluded(organization.FieldBillingMode)
	return u
}

// SetBalance sets the "balance" field.
func (u *OrganizationUpsert) SetBalance(v float64) *OrganizationUpsert {
	u.Set(organization.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateBalance() *OrganizationUpsert {
	u.SetExcluded(organization.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *OrganizationUpsert) AddBalance(v float64) *OrganizationUpsert {
	u.Add(organization.FieldBalance, v)
	return u
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrganizationUpsert) SetMonthlyBudgetUsd(v float64) *OrganizationUpsert {
	u.Set(organization.FieldMonthlyBudgetUsd, v)
	return u
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateMonthlyBudgetUsd() *OrganizationUpsert {
	u.SetExcluded(organization.FieldMonthlyBudgetUsd)
	return u
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrganizationUpsert) AddMonthlyBudgetUsd(v float64) *OrganizationUpsert {
	u.Add(organization.FieldMonthlyBudgetUsd, v)
	return u
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrganizationUpsert) ClearMonthlyBudgetUsd() *OrganizationUpsert {
	u.SetNull(organization.FieldMonthlyBudgetUsd)
	return u
}

// SetMaxMembers sets the "max_members" field.
func (u *OrganizationUpsert) SetMaxMembers(v int) *OrganizationUpsert {
	u.Set(organization.FieldMaxMembers, v)
	return u
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateMaxMembers() *OrganizationUpsert {
	u.SetExcluded(organization.FieldMaxMembers)
	return u
}

// AddMaxMembers adds v to the "max_members" field.
func (u *OrganizationUpsert) AddMaxMembers(v int) *OrganizationUpsert {
	u.Add(organization.FieldMaxMembers, v)
	return u
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (u *OrganizationUpsert) SetMaxAPIKeys(v int) *OrganizationUpsert {
	u.Set(organization.FieldMaxAPIKeys, v)
	return u
}

// UpdateMaxAPIKeys sets the "max_api_keys" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateMaxAPIKeys() *OrganizationUpsert {
	u.SetExcluded(organization.FieldMaxAPIKeys)
	return u
}

// AddMaxAPIKeys adds v to the "max_api_keys" field.
func (u *OrganizationUpsert) AddMaxAPIKeys(v int) *OrganizationUpsert {
	u.Add(organization.FieldMaxAPIKeys, v)
	return u
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsert) SetStatus(v string) *OrganizationUpsert {
	u.Set(organization.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateStatus() *OrganizationUpsert {
	u.SetExcluded(organization.FieldStatus)
	return u
}

// SetAuditMode sets the "audit_mode" field.
func (u *OrganizationUpsert) SetAuditMode(v string) *OrganizationUpsert {
	u.Set(organization.FieldAuditMode, v)
	return u
}

// UpdateAuditMode sets the "audit_mode" field to the value that was provided on create.
func (u *OrganizationUpsert) UpdateAuditMode() *OrganizationUpsert {
	u.SetExcluded(organization.FieldAuditMode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationUpsertOne) UpdateNewValues() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(organization.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrganizationUpsertOne) Ignore() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationUpsertOne) DoNothing() *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationCreate.OnConflict
// documentation for more info.
func (u *OrganizationUpsertOne) Update(set func(*OrganizationUpsert)) *OrganizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsertOne) SetUpdatedAt(v time.Time) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateUpdatedAt() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrganizationUpsertOne) SetDeletedAt(v time.Time) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateDeletedAt() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrganizationUpsertOne) ClearDeletedAt() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *OrganizationUpsertOne) SetName(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateName() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *OrganizationUpsertOne) SetSlug(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateSlug() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateSlug()
	})
}

// SetDescription sets the "description" field.
func (u *OrganizationUpsertOne) SetDescription(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateDescription() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrganizationUpsertOne) ClearDescription() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDescription()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsertOne) SetOwnerUserID(v int64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateOwnerUserID() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *OrganizationUpsertOne) SetBillingMode(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateBillingMode() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateBillingMode()
	})
}

// SetBalance sets the "balance" field.
func (u *OrganizationUpsertOne) SetBalance(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *OrganizationUpsertOne) AddBalance(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateBalance() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateBalance()
	})
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrganizationUpsertOne) SetMonthlyBudgetUsd(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMonthlyBudgetUsd(v)
	})
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrganizationUpsertOne) AddMonthlyBudgetUsd(v float64) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMonthlyBudgetUsd(v)
	})
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateMonthlyBudgetUsd() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMonthlyBudgetUsd()
	})
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrganizationUpsertOne) ClearMonthlyBudgetUsd() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearMonthlyBudgetUsd()
	})
}

// SetMaxMembers sets the "max_members" field.
func (u *OrganizationUpsertOne) SetMaxMembers(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMaxMembers(v)
	})
}

// AddMaxMembers adds v to the "max_members" field.
func (u *OrganizationUpsertOne) AddMaxMembers(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMaxMembers(v)
	})
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateMaxMembers() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMaxMembers()
	})
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (u *OrganizationUpsertOne) SetMaxAPIKeys(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMaxAPIKeys(v)
	})
}

// AddMaxAPIKeys adds v to the "max_api_keys" field.
func (u *OrganizationUpsertOne) AddMaxAPIKeys(v int) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMaxAPIKeys(v)
	})
}

// UpdateMaxAPIKeys sets the "max_api_keys" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateMaxAPIKeys() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMaxAPIKeys()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsertOne) SetStatus(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateStatus() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuditMode sets the "audit_mode" field.
func (u *OrganizationUpsertOne) SetAuditMode(v string) *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetAuditMode(v)
	})
}

// UpdateAuditMode sets the "audit_mode" field to the value that was provided on create.
func (u *OrganizationUpsertOne) UpdateAuditMode() *OrganizationUpsertOne {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateAuditMode()
	})
}

// Exec executes the query.
func (u *OrganizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrganizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrganizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrganizationCreateBulk is the builder for creating many Organization entities in bulk.
type OrganizationCreateBulk struct {
	config
	err      error
	builders []*OrganizationCreate
	conflict []sql.ConflictOption
}

// Save creates the Organization entities in the database.
func (_c *OrganizationCreateBulk) Save(ctx context.Context) ([]*Organization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Organization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationCreateBulk) SaveX(ctx context.Context) []*Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Organization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrganizationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrganizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrganizationUpsertBulk {
	_c.conflict = opts
	return &OrganizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrganizationCreateBulk) OnConflictColumns(columns ...string) *OrganizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrganizationUpsertBulk{
		create: _c,
	}
}

// OrganizationUpsertBulk is the builder for "upsert"-ing
// a bulk of Organization nodes.
type OrganizationUpsertBulk struct {
	create *OrganizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrganizationUpsertBulk) UpdateNewValues() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(organization.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Organization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrganizationUpsertBulk) Ignore() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrganizationUpsertBulk) DoNothing() *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrganizationCreateBulk.OnConflict
// documentation for more info.
func (u *OrganizationUpsertBulk) Update(set func(*OrganizationUpsert)) *OrganizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrganizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrganizationUpsertBulk) SetUpdatedAt(v time.Time) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateUpdatedAt() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrganizationUpsertBulk) SetDeletedAt(v time.Time) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateDeletedAt() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrganizationUpsertBulk) ClearDeletedAt() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *OrganizationUpsertBulk) SetName(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateName() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateName()
	})
}

// SetSlug sets the "slug" field.
func (u *OrganizationUpsertBulk) SetSlug(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateSlug() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateSlug()
	})
}

// SetDescription sets the "description" field.
func (u *OrganizationUpsertBulk) SetDescription(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateDescription() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrganizationUpsertBulk) ClearDescription() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearDescription()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *OrganizationUpsertBulk) SetOwnerUserID(v int64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateOwnerUserID() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *OrganizationUpsertBulk) SetBillingMode(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateBillingMode() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateBillingMode()
	})
}

// SetBalance sets the "balance" field.
func (u *OrganizationUpsertBulk) SetBalance(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *OrganizationUpsertBulk) AddBalance(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateBalance() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateBalance()
	})
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrganizationUpsertBulk) SetMonthlyBudgetUsd(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMonthlyBudgetUsd(v)
	})
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrganizationUpsertBulk) AddMonthlyBudgetUsd(v float64) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMonthlyBudgetUsd(v)
	})
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateMonthlyBudgetUsd() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMonthlyBudgetUsd()
	})
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrganizationUpsertBulk) ClearMonthlyBudgetUsd() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.ClearMonthlyBudgetUsd()
	})
}

// SetMaxMembers sets the "max_members" field.
func (u *OrganizationUpsertBulk) SetMaxMembers(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMaxMembers(v)
	})
}

// AddMaxMembers adds v to the "max_members" field.
func (u *OrganizationUpsertBulk) AddMaxMembers(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMaxMembers(v)
	})
}

// UpdateMaxMembers sets the "max_members" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateMaxMembers() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMaxMembers()
	})
}

// SetMaxAPIKeys sets the "max_api_keys" field.
func (u *OrganizationUpsertBulk) SetMaxAPIKeys(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetMaxAPIKeys(v)
	})
}

// AddMaxAPIKeys adds v to the "max_api_keys" field.
func (u *OrganizationUpsertBulk) AddMaxAPIKeys(v int) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.AddMaxAPIKeys(v)
	})
}

// UpdateMaxAPIKeys sets the "max_api_keys" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateMaxAPIKeys() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateMaxAPIKeys()
	})
}

// SetStatus sets the "status" field.
func (u *OrganizationUpsertBulk) SetStatus(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateStatus() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateStatus()
	})
}

// SetAuditMode sets the "audit_mode" field.
func (u *OrganizationUpsertBulk) SetAuditMode(v string) *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.SetAuditMode(v)
	})
}

// UpdateAuditMode sets the "audit_mode" field to the value that was provided on create.
func (u *OrganizationUpsertBulk) UpdateAuditMode() *OrganizationUpsertBulk {
	return u.Update(func(s *OrganizationUpsert) {
		s.UpdateAuditMode()
	})
}

// Exec executes the query.
func (u *OrganizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrganizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrganizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrganizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
