// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/orgproject"
)

// OrgProjectCreate is the builder for creating a OrgProject entity.
type OrgProjectCreate struct {
	config
	mutation *OrgProjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgProjectCreate) SetCreatedAt(v time.Time) *OrgProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableCreatedAt(v *time.Time) *OrgProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgProjectCreate) SetUpdatedAt(v time.Time) *OrgProjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableUpdatedAt(v *time.Time) *OrgProjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrgProjectCreate) SetDeletedAt(v time.Time) *OrgProjectCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableDeletedAt(v *time.Time) *OrgProjectCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *OrgProjectCreate) SetOrgID(v int64) *OrgProjectCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OrgProjectCreate) SetName(v string) *OrgProjectCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OrgProjectCreate) SetDescription(v string) *OrgProjectCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableDescription(v *string) *OrgProjectCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OrgProjectCreate) SetGroupID(v int64) *OrgProjectCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableGroupID(v *int64) *OrgProjectCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAllowedModels sets the "allowed_models" field.
func (_c *OrgProjectCreate) SetAllowedModels(v []string) *OrgProjectCreate {
	_c.mutation.SetAllowedModels(v)
	return _c
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (_c *OrgProjectCreate) SetMonthlyBudgetUsd(v float64) *OrgProjectCreate {
	_c.mutation.SetMonthlyBudgetUsd(v)
	return _c
}

// SetNillableMonthlyBudgetUsd sets the "monthly_budget_usd" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableMonthlyBudgetUsd(v *float64) *OrgProjectCreate {
	if v != nil {
		_c.SetMonthlyBudgetUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *OrgProjectCreate) SetMonthlyUsageUsd(v float64) *OrgProjectCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableMonthlyUsageUsd(v *float64) *OrgProjectCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *OrgProjectCreate) SetMonthlyWindowStart(v time.Time) *OrgProjectCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableMonthlyWindowStart(v *time.Time) *OrgProjectCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrgProjectCreate) SetStatus(v string) *OrgProjectCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrgProjectCreate) SetNillableStatus(v *string) *OrgProjectCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *OrgProjectCreate) SetOrganizationID(id int64) *OrgProjectCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *OrgProjectCreate) SetOrganization(v *Organization) *OrgProjectCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *OrgProjectCreate) SetGroup(v *Group) *OrgProjectCreate {
	return _c.SetGroupID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *OrgProjectCreate) AddAPIKeyIDs(ids ...int64) *OrgProjectCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *OrgProjectCreate) AddAPIKeys(v ...*APIKey) *OrgProjectCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// Mutation returns the OrgProjectMutation object of the builder.
func (_c *OrgProjectCreate) Mutation() *OrgProjectMutation {
	return _c.mutation
}

// Save creates the OrgProject in the database.
func (_c *OrgProjectCreate) Save(ctx context.Context) (*OrgProject, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgProjectCreate) SaveX(ctx context.Context) *OrgProject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgProjectCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if orgproject.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgproject.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := orgproject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if orgproject.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgproject.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orgproject.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := orgproject.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := orgproject.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgProjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrgProject.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrgProject.updated_at"`)}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "OrgProject.org_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OrgProject.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := orgproject.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgProject.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "OrgProject.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrgProject.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := orgproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrgProject.status": %w`, err)}
		}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrgProject.organization"`)}
	}
	return nil
}

func (_c *OrgProjectCreate) sqlSave(ctx context.Context) (*OrgProject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgProjectCreate) createSpec() (*OrgProject, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgProject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orgproject.Table, sqlgraph.NewFieldSpec(orgproject.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orgproject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orgproject.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(orgproject.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(orgproject.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(orgproject.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.AllowedModels(); ok {
		_spec.SetField(orgproject.FieldAllowedModels, field.TypeJSON, value)
		_node.AllowedModels = value
	}
	if value, ok := _c.mutation.MonthlyBudgetUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
		_node.MonthlyBudgetUsd = &value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(orgproject.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(orgproject.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.OrganizationTable,
			Columns: []string{orgproject.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.GroupTable,
			Columns: []string{orgproject.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgProject.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgProjectCreate) OnConflict(opts ...sql.ConflictOption) *OrgProjectUpsertOne {
	_c.conflict = opts
	return &OrgProjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgProjectCreate) OnConflictColumns(columns ...string) *OrgProjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgProjectUpsertOne{
		create: _c,
	}
}

type (
	// OrgProjectUpsertOne is the builder for "upsert"-ing
	//  one OrgProject node.
	OrgProjectUpsertOne struct {
		create *OrgProjectCreate
	}

	// OrgProjectUpsert is the "OnConflict" setter.
	OrgProjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgProjectUpsert) SetUpdatedAt(v time.Time) *OrgProjectUpsert {
	u.Set(orgproject.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateUpdatedAt() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgProjectUpsert) SetDeletedAt(v time.Time) *OrgProjectUpsert {
	u.Set(orgproject.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateDeletedAt() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgProjectUpsert) ClearDeletedAt() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldDeletedAt)
	return u
}

// SetOrgID sets the "org_id" field.
func (u *OrgProjectUpsert) SetOrgID(v int64) *OrgProjectUpsert {
	u.Set(orgproject.FieldOrgID, v)
	return u
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateOrgID() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldOrgID)
	return u
}

// SetName sets the "name" field.
func (u *OrgProjectUpsert) SetName(v string) *OrgProjectUpsert {
	u.Set(orgproject.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateName() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *OrgProjectUpsert) SetDescription(v string) *OrgProjectUpsert {
	u.Set(orgproject.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateDescription() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *OrgProjectUpsert) ClearDescription() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldDescription)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OrgProjectUpsert) SetGroupID(v int64) *OrgProjectUpsert {
	u.Set(orgproject.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateGroupID() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OrgProjectUpsert) ClearGroupID() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldGroupID)
	return u
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OrgProjectUpsert) SetAllowedModels(v []string) *OrgProjectUpsert {
	u.Set(orgproject.FieldAllowedModels, v)
	return u
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateAllowedModels() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldAllowedModels)
	return u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *OrgProjectUpsert) ClearAllowedModels() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldAllowedModels)
	return u
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrgProjectUpsert) SetMonthlyBudgetUsd(v float64) *OrgProjectUpsert {
	u.Set(orgproject.FieldMonthlyBudgetUsd, v)
	return u
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateMonthlyBudgetUsd() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldMonthlyBudgetUsd)
	return u
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrgProjectUpsert) AddMonthlyBudgetUsd(v float64) *OrgProjectUpsert {
	u.Add(orgproject.FieldMonthlyBudgetUsd, v)
	return u
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrgProjectUpsert) ClearMonthlyBudgetUsd() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldMonthlyBudgetUsd)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgProjectUpsert) SetMonthlyUsageUsd(v float64) *OrgProjectUpsert {
	u.Set(orgproject.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateMonthlyUsageUsd() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgProjectUpsert) AddMonthlyUsageUsd(v float64) *OrgProjectUpsert {
	u.Add(orgproject.FieldMonthlyUsageUsd, v)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgProjectUpsert) SetMonthlyWindowStart(v time.Time) *OrgProjectUpsert {
	u.Set(orgproject.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateMonthlyWindowStart() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgProjectUpsert) ClearMonthlyWindowStart() *OrgProjectUpsert {
	u.SetNull(orgproject.FieldMonthlyWindowStart)
	return u
}

// SetStatus sets the "status" field.
func (u *OrgProjectUpsert) SetStatus(v string) *OrgProjectUpsert {
	u.Set(orgproject.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgProjectUpsert) UpdateStatus() *OrgProjectUpsert {
	u.SetExcluded(orgproject.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgProjectUpsertOne) UpdateNewValues() *OrgProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(orgproject.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgProjectUpsertOne) Ignore() *OrgProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgProjectUpsertOne) DoNothing() *OrgProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgProjectCreate.OnConflict
// documentation for more info.
func (u *OrgProjectUpsertOne) Update(set func(*OrgProjectUpsert)) *OrgProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgProjectUpsertOne) SetUpdatedAt(v time.Time) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateUpdatedAt() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgProjectUpsertOne) SetDeletedAt(v time.Time) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateDeletedAt() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgProjectUpsertOne) ClearDeletedAt() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgProjectUpsertOne) SetOrgID(v int64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateOrgID() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateOrgID()
	})
}

// SetName sets the "name" field.
func (u *OrgProjectUpsertOne) SetName(v string) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateName() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *OrgProjectUpsertOne) SetDescription(v string) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateDescription() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrgProjectUpsertOne) ClearDescription() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearDescription()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrgProjectUpsertOne) SetGroupID(v int64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateGroupID() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OrgProjectUpsertOne) ClearGroupID() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearGroupID()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OrgProjectUpsertOne) SetAllowedModels(v []string) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateAllowedModels() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateAllowedModels()
	})
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *OrgProjectUpsertOne) ClearAllowedModels() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearAllowedModels()
	})
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrgProjectUpsertOne) SetMonthlyBudgetUsd(v float64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyBudgetUsd(v)
	})
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrgProjectUpsertOne) AddMonthlyBudgetUsd(v float64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.AddMonthlyBudgetUsd(v)
	})
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateMonthlyBudgetUsd() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyBudgetUsd()
	})
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrgProjectUpsertOne) ClearMonthlyBudgetUsd() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearMonthlyBudgetUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgProjectUpsertOne) SetMonthlyUsageUsd(v float64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgProjectUpsertOne) AddMonthlyUsageUsd(v float64) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateMonthlyUsageUsd() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgProjectUpsertOne) SetMonthlyWindowStart(v time.Time) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateMonthlyWindowStart() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgProjectUpsertOne) ClearMonthlyWindowStart() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetStatus sets the "status" field.
func (u *OrgProjectUpsertOne) SetStatus(v string) *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgProjectUpsertOne) UpdateStatus() *OrgProjectUpsertOne {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OrgProjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgProjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgProjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgProjectUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgProjectUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgProjectCreateBulk is the builder for creating many OrgProject entities in bulk.
type OrgProjectCreateBulk struct {
	config
	err      error
	builders []*OrgProjectCreate
	conflict []sql.ConflictOption
}

// Save creates the OrgProject entities in the database.
func (_c *OrgProjectCreateBulk) Save(ctx context.Context) ([]*OrgProject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrgProject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgProjectCreateBulk) SaveX(ctx context.Context) []*OrgProject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgProject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgProjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgProjectUpsertBulk {
	_c.conflict = opts
	return &OrgProjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgProjectCreateBulk) OnConflictColumns(columns ...string) *OrgProjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgProjectUpsertBulk{
		create: _c,
	}
}

// OrgProjectUpsertBulk is the builder for "upsert"-ing
// a bulk of OrgProject nodes.
type OrgProjectUpsertBulk struct {
	create *OrgProjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgProjectUpsertBulk) UpdateNewValues() *OrgProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(orgproject.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgProject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgProjectUpsertBulk) Ignore() *OrgProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgProjectUpsertBulk) DoNothing() *OrgProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgProjectCreateBulk.OnConflict
// documentation for more info.
func (u *OrgProjectUpsertBulk) Update(set func(*OrgProjectUpsert)) *OrgProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgProjectUpsertBulk) SetUpdatedAt(v time.Time) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateUpdatedAt() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgProjectUpsertBulk) SetDeletedAt(v time.Time) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateDeletedAt() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgProjectUpsertBulk) ClearDeletedAt() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgProjectUpsertBulk) SetOrgID(v int64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateOrgID() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateOrgID()
	})
}

// SetName sets the "name" field.
func (u *OrgProjectUpsertBulk) SetName(v string) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateName() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *OrgProjectUpsertBulk) SetDescription(v string) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateDescription() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *OrgProjectUpsertBulk) ClearDescription() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearDescription()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrgProjectUpsertBulk) SetGroupID(v int64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateGroupID() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *OrgProjectUpsertBulk) ClearGroupID() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearGroupID()
	})
}

// SetAllowedModels sets the "allowed_models" field.
func (u *OrgProjectUpsertBulk) SetAllowedModels(v []string) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetAllowedModels(v)
	})
}

// UpdateAllowedModels sets the "allowed_models" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateAllowedModels() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateAllowedModels()
	})
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (u *OrgProjectUpsertBulk) ClearAllowedModels() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearAllowedModels()
	})
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (u *OrgProjectUpsertBulk) SetMonthlyBudgetUsd(v float64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyBudgetUsd(v)
	})
}

// AddMonthlyBudgetUsd adds v to the "monthly_budget_usd" field.
func (u *OrgProjectUpsertBulk) AddMonthlyBudgetUsd(v float64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.AddMonthlyBudgetUsd(v)
	})
}

// UpdateMonthlyBudgetUsd sets the "monthly_budget_usd" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateMonthlyBudgetUsd() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyBudgetUsd()
	})
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (u *OrgProjectUpsertBulk) ClearMonthlyBudgetUsd() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearMonthlyBudgetUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgProjectUpsertBulk) SetMonthlyUsageUsd(v float64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgProjectUpsertBulk) AddMonthlyUsageUsd(v float64) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateMonthlyUsageUsd() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgProjectUpsertBulk) SetMonthlyWindowStart(v time.Time) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateMonthlyWindowStart() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgProjectUpsertBulk) ClearMonthlyWindowStart() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetStatus sets the "status" field.
func (u *OrgProjectUpsertBulk) SetStatus(v string) *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgProjectUpsertBulk) UpdateStatus() *OrgProjectUpsertBulk {
	return u.Update(func(s *OrgProjectUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *OrgProjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgProjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgProjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgProjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
