// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/orgproject"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OrgProjectUpdate is the builder for updating OrgProject entities.
type OrgProjectUpdate struct {
	config
	hooks    []Hook
	mutation *OrgProjectMutation
}

// Where appends a list predicates to the OrgProjectUpdate builder.
func (_u *OrgProjectUpdate) Where(ps ...predicate.OrgProject) *OrgProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgProjectUpdate) SetUpdatedAt(v time.Time) *OrgProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrgProjectUpdate) SetDeletedAt(v time.Time) *OrgProjectUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableDeletedAt(v *time.Time) *OrgProjectUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrgProjectUpdate) ClearDeletedAt() *OrgProjectUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OrgProjectUpdate) SetOrgID(v int64) *OrgProjectUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableOrgID(v *int64) *OrgProjectUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OrgProjectUpdate) SetName(v string) *OrgProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableName(v *string) *OrgProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrgProjectUpdate) SetDescription(v string) *OrgProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableDescription(v *string) *OrgProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OrgProjectUpdate) ClearDescription() *OrgProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OrgProjectUpdate) SetGroupID(v int64) *OrgProjectUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableGroupID(v *int64) *OrgProjectUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *OrgProjectUpdate) ClearGroupID() *OrgProjectUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *OrgProjectUpdate) SetAllowedModels(v []string) *OrgProjectUpdate {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *OrgProjectUpdate) AppendAllowedModels(v []string) *OrgProjectUpdate {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (_u *OrgProjectUpdate) ClearAllowedModels() *OrgProjectUpdate {
	_u.mutation.ClearAllowedModels()
	return _u
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (_u *OrgProjectUpdate) SetMonthlyBudgetUsd(v float64) *OrgProjectUpdate {
	_u.mutation.ResetMonthlyBudgetUsd()
	_u.mutation.SetMonthlyBudgetUsd(v)
	return _u
}

// SetNillableMonthlyBudgetUsd sets the "monthly_budget_usd" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableMonthlyBudgetUsd(v *float64) *OrgProjectUpdate {
	if v != nil {
		_u.SetMonthlyBudgetUsd(*v)
	}
	return _u
}

// AddMonthlyBudgetUsd adds value to the "monthly_budget_usd" field.
func (_u *OrgProjectUpdate) AddMonthlyBudgetUsd(v float64) *OrgProjectUpdate {
	_u.mutation.AddMonthlyBudgetUsd(v)
	return _u
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (_u *OrgProjectUpdate) ClearMonthlyBudgetUsd() *OrgProjectUpdate {
	_u.mutation.ClearMonthlyBudgetUsd()
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *OrgProjectUpdate) SetMonthlyUsageUsd(v float64) *OrgProjectUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableMonthlyUsageUsd(v *float64) *OrgProjectUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *OrgProjectUpdate) AddMonthlyUsageUsd(v float64) *OrgProjectUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *OrgProjectUpdate) SetMonthlyWindowStart(v time.Time) *OrgProjectUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableMonthlyWindowStart(v *time.Time) *OrgProjectUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *OrgProjectUpdate) ClearMonthlyWindowStart() *OrgProjectUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrgProjectUpdate) SetStatus(v string) *OrgProjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrgProjectUpdate) SetNillableStatus(v *string) *OrgProjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *OrgProjectUpdate) SetOrganizationID(id int64) *OrgProjectUpdate {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *OrgProjectUpdate) SetOrganization(v *Organization) *OrgProjectUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OrgProjectUpdate) SetGroup(v *Group) *OrgProjectUpdate {
	return _u.SetGroupID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *OrgProjectUpdate) AddAPIKeyIDs(ids ...int64) *OrgProjectUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *OrgProjectUpdate) AddAPIKeys(v ...*APIKey) *OrgProjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// Mutation returns the OrgProjectMutation object of the builder.
func (_u *OrgProjectUpdate) Mutation() *OrgProjectMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *OrgProjectUpdate) ClearOrganization() *OrgProjectUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OrgProjectUpdate) ClearGroup() *OrgProjectUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *OrgProjectUpdate) ClearAPIKeys() *OrgProjectUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *OrgProjectUpdate) RemoveAPIKeyIDs(ids ...int64) *OrgProjectUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *OrgProjectUpdate) RemoveAPIKeys(v ...*APIKey) *OrgProjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrgProjectUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrgProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrgProjectUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if orgproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orgproject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgProjectUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := orgproject.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgProject.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orgproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrgProject.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgProject.organization"`)
	}
	return nil
}

func (_u *OrgProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgproject.Table, orgproject.Columns, sqlgraph.NewFieldSpec(orgproject.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(orgproject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(orgproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(orgproject.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(orgproject.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(orgproject.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(orgproject.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgproject.FieldAllowedModels, value)
		})
	}
	if _u.mutation.AllowedModelsCleared() {
		_spec.ClearField(orgproject.FieldAllowedModels, field.TypeJSON)
	}
	if value, ok := _u.mutation.MonthlyBudgetUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyBudgetUsd(); ok {
		_spec.AddField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyBudgetUsdCleared() {
		_spec.ClearField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(orgproject.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(orgproject.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(orgproject.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orgproject.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.OrganizationTable,
			Columns: []string{orgproject.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.OrganizationTable,
			Columns: []string{orgproject.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.GroupTable,
			Columns: []string{orgproject.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.GroupTable,
			Columns: []string{orgproject.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrgProjectUpdateOne is the builder for updating a single OrgProject entity.
type OrgProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrgProjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrgProjectUpdateOne) SetUpdatedAt(v time.Time) *OrgProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrgProjectUpdateOne) SetDeletedAt(v time.Time) *OrgProjectUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableDeletedAt(v *time.Time) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrgProjectUpdateOne) ClearDeletedAt() *OrgProjectUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OrgProjectUpdateOne) SetOrgID(v int64) *OrgProjectUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableOrgID(v *int64) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OrgProjectUpdateOne) SetName(v string) *OrgProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableName(v *string) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrgProjectUpdateOne) SetDescription(v string) *OrgProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableDescription(v *string) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OrgProjectUpdateOne) ClearDescription() *OrgProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *OrgProjectUpdateOne) SetGroupID(v int64) *OrgProjectUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableGroupID(v *int64) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *OrgProjectUpdateOne) ClearGroupID() *OrgProjectUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAllowedModels sets the "allowed_models" field.
func (_u *OrgProjectUpdateOne) SetAllowedModels(v []string) *OrgProjectUpdateOne {
	_u.mutation.SetAllowedModels(v)
	return _u
}

// AppendAllowedModels appends value to the "allowed_models" field.
func (_u *OrgProjectUpdateOne) AppendAllowedModels(v []string) *OrgProjectUpdateOne {
	_u.mutation.AppendAllowedModels(v)
	return _u
}

// ClearAllowedModels clears the value of the "allowed_models" field.
func (_u *OrgProjectUpdateOne) ClearAllowedModels() *OrgProjectUpdateOne {
	_u.mutation.ClearAllowedModels()
	return _u
}

// SetMonthlyBudgetUsd sets the "monthly_budget_usd" field.
func (_u *OrgProjectUpdateOne) SetMonthlyBudgetUsd(v float64) *OrgProjectUpdateOne {
	_u.mutation.ResetMonthlyBudgetUsd()
	_u.mutation.SetMonthlyBudgetUsd(v)
	return _u
}

// SetNillableMonthlyBudgetUsd sets the "monthly_budget_usd" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableMonthlyBudgetUsd(v *float64) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetMonthlyBudgetUsd(*v)
	}
	return _u
}

// AddMonthlyBudgetUsd adds value to the "monthly_budget_usd" field.
func (_u *OrgProjectUpdateOne) AddMonthlyBudgetUsd(v float64) *OrgProjectUpdateOne {
	_u.mutation.AddMonthlyBudgetUsd(v)
	return _u
}

// ClearMonthlyBudgetUsd clears the value of the "monthly_budget_usd" field.
func (_u *OrgProjectUpdateOne) ClearMonthlyBudgetUsd() *OrgProjectUpdateOne {
	_u.mutation.ClearMonthlyBudgetUsd()
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *OrgProjectUpdateOne) SetMonthlyUsageUsd(v float64) *OrgProjectUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *OrgProjectUpdateOne) AddMonthlyUsageUsd(v float64) *OrgProjectUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *OrgProjectUpdateOne) SetMonthlyWindowStart(v time.Time) *OrgProjectUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *OrgProjectUpdateOne) ClearMonthlyWindowStart() *OrgProjectUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrgProjectUpdateOne) SetStatus(v string) *OrgProjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrgProjectUpdateOne) SetNillableStatus(v *string) *OrgProjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_u *OrgProjectUpdateOne) SetOrganizationID(id int64) *OrgProjectUpdateOne {
	_u.mutation.SetOrganizationID(id)
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *OrgProjectUpdateOne) SetOrganization(v *Organization) *OrgProjectUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *OrgProjectUpdateOne) SetGroup(v *Group) *OrgProjectUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *OrgProjectUpdateOne) AddAPIKeyIDs(ids ...int64) *OrgProjectUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *OrgProjectUpdateOne) AddAPIKeys(v ...*APIKey) *OrgProjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// Mutation returns the OrgProjectMutation object of the builder.
func (_u *OrgProjectUpdateOne) Mutation() *OrgProjectMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *OrgProjectUpdateOne) ClearOrganization() *OrgProjectUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *OrgProjectUpdateOne) ClearGroup() *OrgProjectUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *OrgProjectUpdateOne) ClearAPIKeys() *OrgProjectUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *OrgProjectUpdateOne) RemoveAPIKeyIDs(ids ...int64) *OrgProjectUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *OrgProjectUpdateOne) RemoveAPIKeys(v ...*APIKey) *OrgProjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// Where appends a list predicates to the OrgProjectUpdate builder.
func (_u *OrgProjectUpdateOne) Where(ps ...predicate.OrgProject) *OrgProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrgProjectUpdateOne) Select(field string, fields ...string) *OrgProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrgProject entity.
func (_u *OrgProjectUpdateOne) Save(ctx context.Context) (*OrgProject, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrgProjectUpdateOne) SaveX(ctx context.Context) *OrgProject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrgProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrgProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrgProjectUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if orgproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orgproject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrgProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := orgproject.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrgProject.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orgproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrgProject.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrgProject.organization"`)
	}
	return nil
}

func (_u *OrgProjectUpdateOne) sqlSave(ctx context.Context) (_node *OrgProject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orgproject.Table, orgproject.Columns, sqlgraph.NewFieldSpec(orgproject.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrgProject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgproject.FieldID)
		for _, f := range fields {
			if !orgproject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orgproject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orgproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(orgproject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(orgproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(orgproject.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(orgproject.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(orgproject.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedModels(); ok {
		_spec.SetField(orgproject.FieldAllowedModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, orgproject.FieldAllowedModels, value)
		})
	}
	if _u.mutation.AllowedModelsCleared() {
		_spec.ClearField(orgproject.FieldAllowedModels, field.TypeJSON)
	}
	if value, ok := _u.mutation.MonthlyBudgetUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyBudgetUsd(); ok {
		_spec.AddField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyBudgetUsdCleared() {
		_spec.ClearField(orgproject.FieldMonthlyBudgetUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(orgproject.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(orgproject.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(orgproject.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(orgproject.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orgproject.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.OrganizationTable,
			Columns: []string{orgproject.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.OrganizationTable,
			Columns: []string{orgproject.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.GroupTable,
			Columns: []string{orgproject.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgproject.GroupTable,
			Columns: []string{orgproject.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orgproject.APIKeysTable,
			Columns: []string{orgproject.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrgProject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orgproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
