// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/orgsubscription"
)

// OrgSubscriptionCreate is the builder for creating a OrgSubscription entity.
type OrgSubscriptionCreate struct {
	config
	mutation *OrgSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrgSubscriptionCreate) SetCreatedAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrgSubscriptionCreate) SetUpdatedAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrgSubscriptionCreate) SetDeletedAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableDeletedAt(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *OrgSubscriptionCreate) SetOrgID(v int64) *OrgSubscriptionCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *OrgSubscriptionCreate) SetGroupID(v int64) *OrgSubscriptionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *OrgSubscriptionCreate) SetStartsAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OrgSubscriptionCreate) SetExpiresAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrgSubscriptionCreate) SetStatus(v string) *OrgSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableStatus(v *string) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *OrgSubscriptionCreate) SetDailyWindowStart(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableDailyWindowStart(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *OrgSubscriptionCreate) SetWeeklyWindowStart(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableWeeklyWindowStart(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *OrgSubscriptionCreate) SetMonthlyWindowStart(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableMonthlyWindowStart(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *OrgSubscriptionCreate) SetDailyUsageUsd(v float64) *OrgSubscriptionCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableDailyUsageUsd(v *float64) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *OrgSubscriptionCreate) SetWeeklyUsageUsd(v float64) *OrgSubscriptionCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableWeeklyUsageUsd(v *float64) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *OrgSubscriptionCreate) SetMonthlyUsageUsd(v float64) *OrgSubscriptionCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableMonthlyUsageUsd(v *float64) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *OrgSubscriptionCreate) SetAssignedBy(v int64) *OrgSubscriptionCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableAssignedBy(v *int64) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *OrgSubscriptionCreate) SetAssignedAt(v time.Time) *OrgSubscriptionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableAssignedAt(v *time.Time) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *OrgSubscriptionCreate) SetNotes(v string) *OrgSubscriptionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *OrgSubscriptionCreate) SetNillableNotes(v *string) *OrgSubscriptionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization" edge to the Organization entity by ID.
func (_c *OrgSubscriptionCreate) SetOrganizationID(id int64) *OrgSubscriptionCreate {
	_c.mutation.SetOrganizationID(id)
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *OrgSubscriptionCreate) SetOrganization(v *Organization) *OrgSubscriptionCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *OrgSubscriptionCreate) SetGroup(v *Group) *OrgSubscriptionCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the OrgSubscriptionMutation object of the builder.
func (_c *OrgSubscriptionCreate) Mutation() *OrgSubscriptionMutation {
	return _c.mutation
}

// Save creates the OrgSubscription in the database.
func (_c *OrgSubscriptionCreate) Save(ctx context.Context) (*OrgSubscription, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrgSubscriptionCreate) SaveX(ctx context.Context) *OrgSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrgSubscriptionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if orgsubscription.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgsubscription.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := orgsubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if orgsubscription.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orgsubscription.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orgsubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := orgsubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := orgsubscription.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := orgsubscription.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := orgsubscription.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		if orgsubscription.DefaultAssignedAt == nil {
			return fmt.Errorf("ent: uninitialized orgsubscription.DefaultAssignedAt (forgotten import ent/runtime?)")
		}
		v := orgsubscription.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrgSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrgSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrgSubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "OrgSubscription.org_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "OrgSubscription.group_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "OrgSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OrgSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrgSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := orgsubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrgSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "OrgSubscription.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "OrgSubscription.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "OrgSubscription.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "OrgSubscription.assigned_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrgSubscription.organization"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "OrgSubscription.group"`)}
	}
	return nil
}

func (_c *OrgSubscriptionCreate) sqlSave(ctx context.Context) (*OrgSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrgSubscriptionCreate) createSpec() (*OrgSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &OrgSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orgsubscription.Table, sqlgraph.NewFieldSpec(orgsubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orgsubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orgsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(orgsubscription.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(orgsubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(orgsubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(orgsubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(orgsubscription.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(orgsubscription.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(orgsubscription.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(orgsubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(orgsubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(orgsubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(orgsubscription.FieldAssignedBy, field.TypeInt64, value)
		_node.AssignedBy = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(orgsubscription.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(orgsubscription.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgsubscription.OrganizationTable,
			Columns: []string{orgsubscription.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orgsubscription.GroupTable,
			Columns: []string{orgsubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgSubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *OrgSubscriptionUpsertOne {
	_c.conflict = opts
	return &OrgSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgSubscriptionCreate) OnConflictColumns(columns ...string) *OrgSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// OrgSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one OrgSubscription node.
	OrgSubscriptionUpsertOne struct {
		create *OrgSubscriptionCreate
	}

	// OrgSubscriptionUpsert is the "OnConflict" setter.
	OrgSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgSubscriptionUpsert) SetUpdatedAt(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateUpdatedAt() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgSubscriptionUpsert) SetDeletedAt(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateDeletedAt() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgSubscriptionUpsert) ClearDeletedAt() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldDeletedAt)
	return u
}

// SetOrgID sets the "org_id" field.
func (u *OrgSubscriptionUpsert) SetOrgID(v int64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldOrgID, v)
	return u
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateOrgID() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldOrgID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *OrgSubscriptionUpsert) SetGroupID(v int64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateGroupID() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldGroupID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *OrgSubscriptionUpsert) SetStartsAt(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateStartsAt() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OrgSubscriptionUpsert) SetExpiresAt(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateExpiresAt() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *OrgSubscriptionUpsert) SetStatus(v string) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateStatus() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldStatus)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *OrgSubscriptionUpsert) SetDailyWindowStart(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateDailyWindowStart() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *OrgSubscriptionUpsert) ClearDailyWindowStart() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *OrgSubscriptionUpsert) SetWeeklyWindowStart(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateWeeklyWindowStart() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *OrgSubscriptionUpsert) ClearWeeklyWindowStart() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgSubscriptionUpsert) SetMonthlyWindowStart(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateMonthlyWindowStart() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgSubscriptionUpsert) ClearMonthlyWindowStart() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldMonthlyWindowStart)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsert) SetDailyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateDailyUsageUsd() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsert) AddDailyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Add(orgsubscription.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsert) SetWeeklyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateWeeklyUsageUsd() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsert) AddWeeklyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Add(orgsubscription.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsert) SetMonthlyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateMonthlyUsageUsd() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsert) AddMonthlyUsageUsd(v float64) *OrgSubscriptionUpsert {
	u.Add(orgsubscription.FieldMonthlyUsageUsd, v)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *OrgSubscriptionUpsert) SetAssignedBy(v int64) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateAssignedBy() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldAssignedBy)
	return u
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *OrgSubscriptionUpsert) AddAssignedBy(v int64) *OrgSubscriptionUpsert {
	u.Add(orgsubscription.FieldAssignedBy, v)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *OrgSubscriptionUpsert) ClearAssignedBy() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldAssignedBy)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *OrgSubscriptionUpsert) SetAssignedAt(v time.Time) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateAssignedAt() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldAssignedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *OrgSubscriptionUpsert) SetNotes(v string) *OrgSubscriptionUpsert {
	u.Set(orgsubscription.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrgSubscriptionUpsert) UpdateNotes() *OrgSubscriptionUpsert {
	u.SetExcluded(orgsubscription.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *OrgSubscriptionUpsert) ClearNotes() *OrgSubscriptionUpsert {
	u.SetNull(orgsubscription.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgSubscriptionUpsertOne) UpdateNewValues() *OrgSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(orgsubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrgSubscriptionUpsertOne) Ignore() *OrgSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgSubscriptionUpsertOne) DoNothing() *OrgSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgSubscriptionCreate.OnConflict
// documentation for more info.
func (u *OrgSubscriptionUpsertOne) Update(set func(*OrgSubscriptionUpsert)) *OrgSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateUpdatedAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgSubscriptionUpsertOne) SetDeletedAt(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateDeletedAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgSubscriptionUpsertOne) ClearDeletedAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgSubscriptionUpsertOne) SetOrgID(v int64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateOrgID() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateOrgID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrgSubscriptionUpsertOne) SetGroupID(v int64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateGroupID() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *OrgSubscriptionUpsertOne) SetStartsAt(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateStartsAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OrgSubscriptionUpsertOne) SetExpiresAt(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateExpiresAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *OrgSubscriptionUpsertOne) SetStatus(v string) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateStatus() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *OrgSubscriptionUpsertOne) SetDailyWindowStart(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateDailyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *OrgSubscriptionUpsertOne) ClearDailyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *OrgSubscriptionUpsertOne) SetWeeklyWindowStart(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateWeeklyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *OrgSubscriptionUpsertOne) ClearWeeklyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgSubscriptionUpsertOne) SetMonthlyWindowStart(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateMonthlyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgSubscriptionUpsertOne) ClearMonthlyWindowStart() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) SetDailyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) AddDailyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateDailyUsageUsd() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) SetWeeklyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) AddWeeklyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateWeeklyUsageUsd() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) SetMonthlyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsertOne) AddMonthlyUsageUsd(v float64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateMonthlyUsageUsd() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *OrgSubscriptionUpsertOne) SetAssignedBy(v int64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *OrgSubscriptionUpsertOne) AddAssignedBy(v int64) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateAssignedBy() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *OrgSubscriptionUpsertOne) ClearAssignedBy() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *OrgSubscriptionUpsertOne) SetAssignedAt(v time.Time) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateAssignedAt() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *OrgSubscriptionUpsertOne) SetNotes(v string) *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertOne) UpdateNotes() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *OrgSubscriptionUpsertOne) ClearNotes() *OrgSubscriptionUpsertOne {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *OrgSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrgSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrgSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrgSubscriptionCreateBulk is the builder for creating many OrgSubscription entities in bulk.
type OrgSubscriptionCreateBulk struct {
	config
	err      error
	builders []*OrgSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the OrgSubscription entities in the database.
func (_c *OrgSubscriptionCreateBulk) Save(ctx context.Context) ([]*OrgSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrgSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrgSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrgSubscriptionCreateBulk) SaveX(ctx context.Context) []*OrgSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrgSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrgSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrgSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrgSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrgSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrgSubscriptionUpsertBulk {
	_c.conflict = opts
	return &OrgSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrgSubscriptionCreateBulk) OnConflictColumns(columns ...string) *OrgSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrgSubscriptionUpsertBulk{
		create: _c,
	}
}

// OrgSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of OrgSubscription nodes.
type OrgSubscriptionUpsertBulk struct {
	create *OrgSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrgSubscriptionUpsertBulk) UpdateNewValues() *OrgSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(orgsubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrgSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrgSubscriptionUpsertBulk) Ignore() *OrgSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrgSubscriptionUpsertBulk) DoNothing() *OrgSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrgSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *OrgSubscriptionUpsertBulk) Update(set func(*OrgSubscriptionUpsert)) *OrgSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrgSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrgSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateUpdatedAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrgSubscriptionUpsertBulk) SetDeletedAt(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateDeletedAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrgSubscriptionUpsertBulk) ClearDeletedAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrgID sets the "org_id" field.
func (u *OrgSubscriptionUpsertBulk) SetOrgID(v int64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateOrgID() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateOrgID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *OrgSubscriptionUpsertBulk) SetGroupID(v int64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateGroupID() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *OrgSubscriptionUpsertBulk) SetStartsAt(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateStartsAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OrgSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateExpiresAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *OrgSubscriptionUpsertBulk) SetStatus(v string) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateStatus() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *OrgSubscriptionUpsertBulk) SetDailyWindowStart(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateDailyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *OrgSubscriptionUpsertBulk) ClearDailyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *OrgSubscriptionUpsertBulk) SetWeeklyWindowStart(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateWeeklyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *OrgSubscriptionUpsertBulk) ClearWeeklyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *OrgSubscriptionUpsertBulk) SetMonthlyWindowStart(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateMonthlyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *OrgSubscriptionUpsertBulk) ClearMonthlyWindowStart() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) SetDailyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) AddDailyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateDailyUsageUsd() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) SetWeeklyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) AddWeeklyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateWeeklyUsageUsd() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) SetMonthlyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *OrgSubscriptionUpsertBulk) AddMonthlyUsageUsd(v float64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateMonthlyUsageUsd() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *OrgSubscriptionUpsertBulk) SetAssignedBy(v int64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// AddAssignedBy adds v to the "assigned_by" field.
func (u *OrgSubscriptionUpsertBulk) AddAssignedBy(v int64) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.AddAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateAssignedBy() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *OrgSubscriptionUpsertBulk) ClearAssignedBy() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *OrgSubscriptionUpsertBulk) SetAssignedAt(v time.Time) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateAssignedAt() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *OrgSubscriptionUpsertBulk) SetNotes(v string) *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrgSubscriptionUpsertBulk) UpdateNotes() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *OrgSubscriptionUpsertBulk) ClearNotes() *OrgSubscriptionUpsertBulk {
	return u.Update(func(s *OrgSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *OrgSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrgSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrgSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrgSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
