// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *PaymentOrderCreate) SetOrderNo(v string) *PaymentOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v int64) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlanKey sets the "plan_key" field.
func (_c *PaymentOrderCreate) SetPlanKey(v string) *PaymentOrderCreate {
	_c.mutation.SetPlanKey(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PaymentOrderCreate) SetGroupID(v int64) *PaymentOrderCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAmountFen sets the "amount_fen" field.
func (_c *PaymentOrderCreate) SetAmountFen(v int) *PaymentOrderCreate {
	_c.mutation.SetAmountFen(v)
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *PaymentOrderCreate) SetValidityDays(v int) *PaymentOrderCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableValidityDays(v *int) *PaymentOrderCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetOrderType sets the "order_type" field.
func (_c *PaymentOrderCreate) SetOrderType(v string) *PaymentOrderCreate {
	_c.mutation.SetOrderType(v)
	return _c
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableOrderType(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetOrderType(*v)
	}
	return _c
}

// SetBalanceAmount sets the "balance_amount" field.
func (_c *PaymentOrderCreate) SetBalanceAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetBalanceAmount(v)
	return _c
}

// SetNillableBalanceAmount sets the "balance_amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableBalanceAmount(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetBalanceAmount(*v)
	}
	return _c
}

// SetPromoCode sets the "promo_code" field.
func (_c *PaymentOrderCreate) SetPromoCode(v string) *PaymentOrderCreate {
	_c.mutation.SetPromoCode(v)
	return _c
}

// SetNillablePromoCode sets the "promo_code" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePromoCode(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetPromoCode(*v)
	}
	return _c
}

// SetDiscountAmount sets the "discount_amount" field.
func (_c *PaymentOrderCreate) SetDiscountAmount(v int) *PaymentOrderCreate {
	_c.mutation.SetDiscountAmount(v)
	return _c
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableDiscountAmount(v *int) *PaymentOrderCreate {
	if v != nil {
		_c.SetDiscountAmount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPayMethod sets the "pay_method" field.
func (_c *PaymentOrderCreate) SetPayMethod(v string) *PaymentOrderCreate {
	_c.mutation.SetPayMethod(v)
	return _c
}

// SetNillablePayMethod sets the "pay_method" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePayMethod(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetPayMethod(*v)
	}
	return _c
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (_c *PaymentOrderCreate) SetWechatTransactionID(v string) *PaymentOrderCreate {
	_c.mutation.SetWechatTransactionID(v)
	return _c
}

// SetNillableWechatTransactionID sets the "wechat_transaction_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableWechatTransactionID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetWechatTransactionID(*v)
	}
	return _c
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_c *PaymentOrderCreate) SetAlipayTradeNo(v string) *PaymentOrderCreate {
	_c.mutation.SetAlipayTradeNo(v)
	return _c
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAlipayTradeNo(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetAlipayTradeNo(*v)
	}
	return _c
}

// SetCodeURL sets the "code_url" field.
func (_c *PaymentOrderCreate) SetCodeURL(v string) *PaymentOrderCreate {
	_c.mutation.SetCodeURL(v)
	return _c
}

// SetNillableCodeURL sets the "code_url" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCodeURL(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetCodeURL(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *PaymentOrderCreate) SetExpiredAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentOrderCreate) SetUpdatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentOrderCreate) SetID(v int64) *PaymentOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := paymentorder.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		v := paymentorder.DefaultOrderType
		_c.mutation.SetOrderType(v)
	}
	if _, ok := _c.mutation.BalanceAmount(); !ok {
		v := paymentorder.DefaultBalanceAmount
		_c.mutation.SetBalanceAmount(v)
	}
	if _, ok := _c.mutation.PromoCode(); !ok {
		v := paymentorder.DefaultPromoCode
		_c.mutation.SetPromoCode(v)
	}
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		v := paymentorder.DefaultDiscountAmount
		_c.mutation.SetDiscountAmount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PayMethod(); !ok {
		v := paymentorder.DefaultPayMethod
		_c.mutation.SetPayMethod(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "PaymentOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := _c.mutation.PlanKey(); !ok {
		return &ValidationError{Name: "plan_key", err: errors.New(`ent: missing required field "PaymentOrder.plan_key"`)}
	}
	if v, ok := _c.mutation.PlanKey(); ok {
		if err := paymentorder.PlanKeyValidator(v); err != nil {
			return &ValidationError{Name: "plan_key", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.plan_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "PaymentOrder.group_id"`)}
	}
	if _, ok := _c.mutation.AmountFen(); !ok {
		return &ValidationError{Name: "amount_fen", err: errors.New(`ent: missing required field "PaymentOrder.amount_fen"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "PaymentOrder.validity_days"`)}
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		return &ValidationError{Name: "order_type", err: errors.New(`ent: missing required field "PaymentOrder.order_type"`)}
	}
	if v, ok := _c.mutation.OrderType(); ok {
		if err := paymentorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceAmount(); !ok {
		return &ValidationError{Name: "balance_amount", err: errors.New(`ent: missing required field "PaymentOrder.balance_amount"`)}
	}
	if v, ok := _c.mutation.PromoCode(); ok {
		if err := paymentorder.PromoCodeValidator(v); err != nil {
			return &ValidationError{Name: "promo_code", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.promo_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		return &ValidationError{Name: "discount_amount", err: errors.New(`ent: missing required field "PaymentOrder.discount_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayMethod(); !ok {
		return &ValidationError{Name: "pay_method", err: errors.New(`ent: missing required field "PaymentOrder.pay_method"`)}
	}
	if v, ok := _c.mutation.PayMethod(); ok {
		if err := paymentorder.PayMethodValidator(v); err != nil {
			return &ValidationError{Name: "pay_method", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.pay_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WechatTransactionID(); ok {
		if err := paymentorder.WechatTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wechat_transaction_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wechat_transaction_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "PaymentOrder.expired_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.PlanKey(); ok {
		_spec.SetField(paymentorder.FieldPlanKey, field.TypeString, value)
		_node.PlanKey = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(paymentorder.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.AmountFen(); ok {
		_spec.SetField(paymentorder.FieldAmountFen, field.TypeInt, value)
		_node.AmountFen = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(paymentorder.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.OrderType(); ok {
		_spec.SetField(paymentorder.FieldOrderType, field.TypeString, value)
		_node.OrderType = value
	}
	if value, ok := _c.mutation.BalanceAmount(); ok {
		_spec.SetField(paymentorder.FieldBalanceAmount, field.TypeFloat64, value)
		_node.BalanceAmount = value
	}
	if value, ok := _c.mutation.PromoCode(); ok {
		_spec.SetField(paymentorder.FieldPromoCode, field.TypeString, value)
		_node.PromoCode = value
	}
	if value, ok := _c.mutation.DiscountAmount(); ok {
		_spec.SetField(paymentorder.FieldDiscountAmount, field.TypeInt, value)
		_node.DiscountAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PayMethod(); ok {
		_spec.SetField(paymentorder.FieldPayMethod, field.TypeString, value)
		_node.PayMethod = value
	}
	if value, ok := _c.mutation.WechatTransactionID(); ok {
		_spec.SetField(paymentorder.FieldWechatTransactionID, field.TypeString, value)
		_node.WechatTransactionID = &value
	}
	if value, ok := _c.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
		_node.AlipayTradeNo = &value
	}
	if value, ok := _c.mutation.CodeURL(); ok {
		_spec.SetField(paymentorder.FieldCodeURL, field.TypeString, value)
		_node.CodeURL = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	_c.conflict = opts
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsert) SetOrderNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateOrderNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetPlanKey sets the "plan_key" field.
func (u *PaymentOrderUpsert) SetPlanKey(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPlanKey, v)
	return u
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePlanKey() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPlanKey)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PaymentOrderUpsert) SetGroupID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateGroupID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *PaymentOrderUpsert) AddGroupID(v int64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldGroupID, v)
	return u
}

// SetAmountFen sets the "amount_fen" field.
func (u *PaymentOrderUpsert) SetAmountFen(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmountFen, v)
	return u
}

// UpdateAmountFen sets the "amount_fen" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmountFen() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmountFen)
	return u
}

// AddAmountFen adds v to the "amount_fen" field.
func (u *PaymentOrderUpsert) AddAmountFen(v int) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmountFen, v)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentOrderUpsert) SetValidityDays(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateValidityDays() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentOrderUpsert) AddValidityDays(v int) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldValidityDays, v)
	return u
}

// SetOrderType sets the "order_type" field.
func (u *PaymentOrderUpsert) SetOrderType(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldOrderType, v)
	return u
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateOrderType() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldOrderType)
	return u
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *PaymentOrderUpsert) SetBalanceAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldBalanceAmount, v)
	return u
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateBalanceAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldBalanceAmount)
	return u
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *PaymentOrderUpsert) AddBalanceAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldBalanceAmount, v)
	return u
}

// SetPromoCode sets the "promo_code" field.
func (u *PaymentOrderUpsert) SetPromoCode(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPromoCode, v)
	return u
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePromoCode() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPromoCode)
	return u
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PaymentOrderUpsert) ClearPromoCode() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPromoCode)
	return u
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PaymentOrderUpsert) SetDiscountAmount(v int) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldDiscountAmount, v)
	return u
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateDiscountAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldDiscountAmount)
	return u
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PaymentOrderUpsert) AddDiscountAmount(v int) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldDiscountAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// SetPayMethod sets the "pay_method" field.
func (u *PaymentOrderUpsert) SetPayMethod(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPayMethod, v)
	return u
}

// UpdatePayMethod sets the "pay_method" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePayMethod() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPayMethod)
	return u
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *PaymentOrderUpsert) SetWechatTransactionID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldWechatTransactionID, v)
	return u
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateWechatTransactionID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldWechatTransactionID)
	return u
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *PaymentOrderUpsert) ClearWechatTransactionID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldWechatTransactionID)
	return u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsert) SetAlipayTradeNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAlipayTradeNo, v)
	return u
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAlipayTradeNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAlipayTradeNo)
	return u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsert) ClearAlipayTradeNo() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldAlipayTradeNo)
	return u
}

// SetCodeURL sets the "code_url" field.
func (u *PaymentOrderUpsert) SetCodeURL(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCodeURL, v)
	return u
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCodeURL() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCodeURL)
	return u
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *PaymentOrderUpsert) ClearCodeURL() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldCodeURL)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsert) SetPaidAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaidAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsert) ClearPaidAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPaidAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsert) SetExpiredAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateExpiredAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldExpiredAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsert) SetUpdatedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUpdatedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(paymentorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertOne) SetOrderNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanKey sets the "plan_key" field.
func (u *PaymentOrderUpsertOne) SetPlanKey(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPlanKey(v)
	})
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePlanKey() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePlanKey()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PaymentOrderUpsertOne) SetGroupID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PaymentOrderUpsertOne) AddGroupID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateGroupID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmountFen sets the "amount_fen" field.
func (u *PaymentOrderUpsertOne) SetAmountFen(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmountFen(v)
	})
}

// AddAmountFen adds v to the "amount_fen" field.
func (u *PaymentOrderUpsertOne) AddAmountFen(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmountFen(v)
	})
}

// UpdateAmountFen sets the "amount_fen" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmountFen() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmountFen()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentOrderUpsertOne) SetValidityDays(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentOrderUpsertOne) AddValidityDays(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateValidityDays() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateValidityDays()
	})
}

// SetOrderType sets the "order_type" field.
func (u *PaymentOrderUpsertOne) SetOrderType(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateOrderType() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *PaymentOrderUpsertOne) SetBalanceAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetBalanceAmount(v)
	})
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *PaymentOrderUpsertOne) AddBalanceAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddBalanceAmount(v)
	})
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateBalanceAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateBalanceAmount()
	})
}

// SetPromoCode sets the "promo_code" field.
func (u *PaymentOrderUpsertOne) SetPromoCode(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPromoCode(v)
	})
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePromoCode() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePromoCode()
	})
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PaymentOrderUpsertOne) ClearPromoCode() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPromoCode()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PaymentOrderUpsertOne) SetDiscountAmount(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PaymentOrderUpsertOne) AddDiscountAmount(v int) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateDiscountAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPayMethod sets the "pay_method" field.
func (u *PaymentOrderUpsertOne) SetPayMethod(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayMethod(v)
	})
}

// UpdatePayMethod sets the "pay_method" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePayMethod() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayMethod()
	})
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *PaymentOrderUpsertOne) SetWechatTransactionID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetWechatTransactionID(v)
	})
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateWechatTransactionID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateWechatTransactionID()
	})
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *PaymentOrderUpsertOne) ClearWechatTransactionID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearWechatTransactionID()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsertOne) SetAlipayTradeNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAlipayTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsertOne) ClearAlipayTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetCodeURL sets the "code_url" field.
func (u *PaymentOrderUpsertOne) SetCodeURL(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCodeURL(v)
	})
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCodeURL() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCodeURL()
	})
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *PaymentOrderUpsertOne) ClearCodeURL() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCodeURL()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertOne) SetPaidAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertOne) ClearPaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertOne) SetExpiredAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateExpiredAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUpdatedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(paymentorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(paymentorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertBulk) SetOrderNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetPlanKey sets the "plan_key" field.
func (u *PaymentOrderUpsertBulk) SetPlanKey(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPlanKey(v)
	})
}

// UpdatePlanKey sets the "plan_key" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePlanKey() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePlanKey()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PaymentOrderUpsertBulk) SetGroupID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PaymentOrderUpsertBulk) AddGroupID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateGroupID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmountFen sets the "amount_fen" field.
func (u *PaymentOrderUpsertBulk) SetAmountFen(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmountFen(v)
	})
}

// AddAmountFen adds v to the "amount_fen" field.
func (u *PaymentOrderUpsertBulk) AddAmountFen(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmountFen(v)
	})
}

// UpdateAmountFen sets the "amount_fen" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmountFen() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmountFen()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PaymentOrderUpsertBulk) SetValidityDays(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PaymentOrderUpsertBulk) AddValidityDays(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateValidityDays() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateValidityDays()
	})
}

// SetOrderType sets the "order_type" field.
func (u *PaymentOrderUpsertBulk) SetOrderType(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateOrderType() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetBalanceAmount sets the "balance_amount" field.
func (u *PaymentOrderUpsertBulk) SetBalanceAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetBalanceAmount(v)
	})
}

// AddBalanceAmount adds v to the "balance_amount" field.
func (u *PaymentOrderUpsertBulk) AddBalanceAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddBalanceAmount(v)
	})
}

// UpdateBalanceAmount sets the "balance_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateBalanceAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateBalanceAmount()
	})
}

// SetPromoCode sets the "promo_code" field.
func (u *PaymentOrderUpsertBulk) SetPromoCode(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPromoCode(v)
	})
}

// UpdatePromoCode sets the "promo_code" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePromoCode() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePromoCode()
	})
}

// ClearPromoCode clears the value of the "promo_code" field.
func (u *PaymentOrderUpsertBulk) ClearPromoCode() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPromoCode()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *PaymentOrderUpsertBulk) SetDiscountAmount(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *PaymentOrderUpsertBulk) AddDiscountAmount(v int) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateDiscountAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPayMethod sets the "pay_method" field.
func (u *PaymentOrderUpsertBulk) SetPayMethod(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayMethod(v)
	})
}

// UpdatePayMethod sets the "pay_method" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePayMethod() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayMethod()
	})
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *PaymentOrderUpsertBulk) SetWechatTransactionID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetWechatTransactionID(v)
	})
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateWechatTransactionID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateWechatTransactionID()
	})
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *PaymentOrderUpsertBulk) ClearWechatTransactionID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearWechatTransactionID()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsertBulk) SetAlipayTradeNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAlipayTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsertBulk) ClearAlipayTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetCodeURL sets the "code_url" field.
func (u *PaymentOrderUpsertBulk) SetCodeURL(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCodeURL(v)
	})
}

// UpdateCodeURL sets the "code_url" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCodeURL() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCodeURL()
	})
}

// ClearCodeURL clears the value of the "code_url" field.
func (u *PaymentOrderUpsertBulk) ClearCodeURL() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCodeURL()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertBulk) ClearPaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertBulk) SetExpiredAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateExpiredAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUpdatedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
