// Code generated by ent, DO NOT EDIT.

package organization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldSlug, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldDescription, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOwnerUserID, v))
}

// BillingMode applies equality check predicate on the "billing_mode" field. It's identical to BillingModeEQ.
func BillingMode(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldBillingMode, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldBalance, v))
}

// MonthlyBudgetUsd applies equality check predicate on the "monthly_budget_usd" field. It's identical to MonthlyBudgetUsdEQ.
func MonthlyBudgetUsd(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMonthlyBudgetUsd, v))
}

// MaxMembers applies equality check predicate on the "max_members" field. It's identical to MaxMembersEQ.
func MaxMembers(v int) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMaxMembers, v))
}

// MaxAPIKeys applies equality check predicate on the "max_api_keys" field. It's identical to MaxAPIKeysEQ.
func MaxAPIKeys(v int) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMaxAPIKeys, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldStatus, v))
}

// AuditMode applies equality check predicate on the "audit_mode" field. It's identical to AuditModeEQ.
func AuditMode(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAuditMode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldSlug, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldDescription, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// BillingModeEQ applies the EQ predicate on the "billing_mode" field.
func BillingModeEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldBillingMode, v))
}

// BillingModeNEQ applies the NEQ predicate on the "billing_mode" field.
func BillingModeNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldBillingMode, v))
}

// BillingModeIn applies the In predicate on the "billing_mode" field.
func BillingModeIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldBillingMode, vs...))
}

// BillingModeNotIn applies the NotIn predicate on the "billing_mode" field.
func BillingModeNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldBillingMode, vs...))
}

// BillingModeGT applies the GT predicate on the "billing_mode" field.
func BillingModeGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldBillingMode, v))
}

// BillingModeGTE applies the GTE predicate on the "billing_mode" field.
func BillingModeGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldBillingMode, v))
}

// BillingModeLT applies the LT predicate on the "billing_mode" field.
func BillingModeLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldBillingMode, v))
}

// BillingModeLTE applies the LTE predicate on the "billing_mode" field.
func BillingModeLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldBillingMode, v))
}

// BillingModeContains applies the Contains predicate on the "billing_mode" field.
func BillingModeContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldBillingMode, v))
}

// BillingModeHasPrefix applies the HasPrefix predicate on the "billing_mode" field.
func BillingModeHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldBillingMode, v))
}

// BillingModeHasSuffix applies the HasSuffix predicate on the "billing_mode" field.
func BillingModeHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldBillingMode, v))
}

// BillingModeEqualFold applies the EqualFold predicate on the "billing_mode" field.
func BillingModeEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldBillingMode, v))
}

// BillingModeContainsFold applies the ContainsFold predicate on the "billing_mode" field.
func BillingModeContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldBillingMode, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldBalance, v))
}

// MonthlyBudgetUsdEQ applies the EQ predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdNEQ applies the NEQ predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdNEQ(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdIn applies the In predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldMonthlyBudgetUsd, vs...))
}

// MonthlyBudgetUsdNotIn applies the NotIn predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdNotIn(vs ...float64) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldMonthlyBudgetUsd, vs...))
}

// MonthlyBudgetUsdGT applies the GT predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdGT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdGTE applies the GTE predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdGTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdLT applies the LT predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdLT(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdLTE applies the LTE predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdLTE(v float64) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldMonthlyBudgetUsd, v))
}

// MonthlyBudgetUsdIsNil applies the IsNil predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdIsNil() predicate.Organization {
	return predicate.Organization(sql.FieldIsNull(FieldMonthlyBudgetUsd))
}

// MonthlyBudgetUsdNotNil applies the NotNil predicate on the "monthly_budget_usd" field.
func MonthlyBudgetUsdNotNil() predicate.Organization {
	return predicate.Organization(sql.FieldNotNull(FieldMonthlyBudgetUsd))
}

// MaxMembersEQ applies the EQ predicate on the "max_members" field.
func MaxMembersEQ(v int) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMaxMembers, v))
}

// MaxMembersNEQ applies the NEQ predicate on the "max_members" field.
func MaxMembersNEQ(v int) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldMaxMembers, v))
}

// MaxMembersIn applies the In predicate on the "max_members" field.
func MaxMembersIn(vs ...int) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldMaxMembers, vs...))
}

// MaxMembersNotIn applies the NotIn predicate on the "max_members" field.
func MaxMembersNotIn(vs ...int) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldMaxMembers, vs...))
}

// MaxMembersGT applies the GT predicate on the "max_members" field.
func MaxMembersGT(v int) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldMaxMembers, v))
}

// MaxMembersGTE applies the GTE predicate on the "max_members" field.
func MaxMembersGTE(v int) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldMaxMembers, v))
}

// MaxMembersLT applies the LT predicate on the "max_members" field.
func MaxMembersLT(v int) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldMaxMembers, v))
}

// MaxMembersLTE applies the LTE predicate on the "max_members" field.
func MaxMembersLTE(v int) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldMaxMembers, v))
}

// MaxAPIKeysEQ applies the EQ predicate on the "max_api_keys" field.
func MaxAPIKeysEQ(v int) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldMaxAPIKeys, v))
}

// MaxAPIKeysNEQ applies the NEQ predicate on the "max_api_keys" field.
func MaxAPIKeysNEQ(v int) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldMaxAPIKeys, v))
}

// MaxAPIKeysIn applies the In predicate on the "max_api_keys" field.
func MaxAPIKeysIn(vs ...int) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldMaxAPIKeys, vs...))
}

// MaxAPIKeysNotIn applies the NotIn predicate on the "max_api_keys" field.
func MaxAPIKeysNotIn(vs ...int) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldMaxAPIKeys, vs...))
}

// MaxAPIKeysGT applies the GT predicate on the "max_api_keys" field.
func MaxAPIKeysGT(v int) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldMaxAPIKeys, v))
}

// MaxAPIKeysGTE applies the GTE predicate on the "max_api_keys" field.
func MaxAPIKeysGTE(v int) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldMaxAPIKeys, v))
}

// MaxAPIKeysLT applies the LT predicate on the "max_api_keys" field.
func MaxAPIKeysLT(v int) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldMaxAPIKeys, v))
}

// MaxAPIKeysLTE applies the LTE predicate on the "max_api_keys" field.
func MaxAPIKeysLTE(v int) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldMaxAPIKeys, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldStatus, v))
}

// AuditModeEQ applies the EQ predicate on the "audit_mode" field.
func AuditModeEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEQ(FieldAuditMode, v))
}

// AuditModeNEQ applies the NEQ predicate on the "audit_mode" field.
func AuditModeNEQ(v string) predicate.Organization {
	return predicate.Organization(sql.FieldNEQ(FieldAuditMode, v))
}

// AuditModeIn applies the In predicate on the "audit_mode" field.
func AuditModeIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldIn(FieldAuditMode, vs...))
}

// AuditModeNotIn applies the NotIn predicate on the "audit_mode" field.
func AuditModeNotIn(vs ...string) predicate.Organization {
	return predicate.Organization(sql.FieldNotIn(FieldAuditMode, vs...))
}

// AuditModeGT applies the GT predicate on the "audit_mode" field.
func AuditModeGT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGT(FieldAuditMode, v))
}

// AuditModeGTE applies the GTE predicate on the "audit_mode" field.
func AuditModeGTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldGTE(FieldAuditMode, v))
}

// AuditModeLT applies the LT predicate on the "audit_mode" field.
func AuditModeLT(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLT(FieldAuditMode, v))
}

// AuditModeLTE applies the LTE predicate on the "audit_mode" field.
func AuditModeLTE(v string) predicate.Organization {
	return predicate.Organization(sql.FieldLTE(FieldAuditMode, v))
}

// AuditModeContains applies the Contains predicate on the "audit_mode" field.
func AuditModeContains(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContains(FieldAuditMode, v))
}

// AuditModeHasPrefix applies the HasPrefix predicate on the "audit_mode" field.
func AuditModeHasPrefix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasPrefix(FieldAuditMode, v))
}

// AuditModeHasSuffix applies the HasSuffix predicate on the "audit_mode" field.
func AuditModeHasSuffix(v string) predicate.Organization {
	return predicate.Organization(sql.FieldHasSuffix(FieldAuditMode, v))
}

// AuditModeEqualFold applies the EqualFold predicate on the "audit_mode" field.
func AuditModeEqualFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldEqualFold(FieldAuditMode, v))
}

// AuditModeContainsFold applies the ContainsFold predicate on the "audit_mode" field.
func AuditModeContainsFold(v string) predicate.Organization {
	return predicate.Organization(sql.FieldContainsFold(FieldAuditMode, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.OrgMember) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.OrgSubscription) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProjects applies the HasEdge predicate on the "projects" edge.
func HasProjects() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProjectsTable, ProjectsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectsWith applies the HasEdge predicate on the "projects" edge with a given conditions (other predicates).
func HasProjectsWith(preds ...predicate.OrgProject) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newProjectsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditLogs applies the HasEdge predicate on the "audit_logs" edge.
func HasAuditLogs() predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditLogsWith applies the HasEdge predicate on the "audit_logs" edge with a given conditions (other predicates).
func HasAuditLogsWith(preds ...predicate.OrgAuditLog) predicate.Organization {
	return predicate.Organization(func(s *sql.Selector) {
		step := newAuditLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Organization) predicate.Organization {
	return predicate.Organization(sql.NotPredicates(p))
}
